import { TabPane, Table, Tabs, Tag } from "@douyinfe/semi-ui";
import { DataList, DetailWorkspace, EmptyBlock, PageHeader, SideSection, StatusTag, TableEntity } from "@/components/CrmUi";
import { useCrm } from "@/stores/crm-store";
import type { Distributor } from "@/types/crm";
import { navigate } from "@/utils/format";

export function DistributorsPage({ id }: { id?: string }) { return id ? <DistributorDetail id={id} /> : <DistributorList />; }

function DistributorList() {
  const { state } = useCrm();
  const columns = [{ title: "Distributor", dataIndex: "name", width: 240, render: (_: unknown, item: Distributor) => <TableEntity name={item.name} detail={item.code} route={`distributors/${item.id}`} /> }, { title: "Country", dataIndex: "country" }, { title: "Manager", render: (_: unknown, item: Distributor) => state.users.find((user) => user.distributorId === item.id && user.role === "DISTRIBUTOR_MANAGER")?.name || "—" }, { title: "Users", render: (_: unknown, item: Distributor) => state.users.filter((user) => user.distributorId === item.id).length }, { title: "Leads", render: (_: unknown, item: Distributor) => state.leads.filter((lead) => lead.distributorId === item.id).length }, { title: "Deals", render: (_: unknown, item: Distributor) => state.deals.filter((deal) => deal.distributorId === item.id).length }, { title: "Won Deals", render: (_: unknown, item: Distributor) => state.deals.filter((deal) => deal.distributorId === item.id && deal.stage === "WON").length }, { title: "Status", dataIndex: "status", render: (value: Distributor["status"]) => <StatusTag value={value} label={value} /> }];
  return <div className="page"><PageHeader title="Distributors" description="HQ 管理全球渠道范围、用户与产品表现。" /><section className="data-surface"><Table rowKey="id" columns={columns} dataSource={state.distributors.filter((item) => item.id !== "dist-hq")} pagination={false} /></section></div>;
}

function DistributorDetail({ id }: { id: string }) {
  const { state } = useCrm(); const item = state.distributors.find((distributor) => distributor.id === id); if (!item) return <div className="page"><EmptyBlock title="分销商不存在" action={() => navigate("distributors")} /></div>;
  const users = state.users.filter((user) => user.distributorId === id); const leads = state.leads.filter((lead) => lead.distributorId === id); const deals = state.deals.filter((deal) => deal.distributorId === id); const products = state.products.map((product) => ({ product, count: deals.filter((deal) => deal.productId === product.id).length }));
  const rows = (items: Array<{ id: string; name: string }>, route: string) => <div className="related-list">{items.map((current) => <a key={current.id} href={`#${route}/${current.id}`}>{current.name}</a>)}</div>;
  return <DetailWorkspace eyebrow="Management / Distributors" title={item.name} subtitle={`${item.country} · ${item.code}`} backRoute="distributors" tags={<StatusTag value={item.status} label={item.status} />} tabs={<Tabs className="record-tabs"><TabPane tab="Overview" itemKey="overview"><div className="metric-strip"><div><span>Users</span><strong>{users.length}</strong></div><div><span>Leads</span><strong>{leads.length}</strong></div><div><span>Open Deals</span><strong>{deals.filter((deal) => !["WON", "LOST"].includes(deal.stage)).length}</strong></div><div><span>Won Deals</span><strong>{deals.filter((deal) => deal.stage === "WON").length}</strong></div></div></TabPane><TabPane tab="Users" itemKey="users"><div className="related-list">{users.map((user) => <span key={user.id}>{user.name} · {user.title}</span>)}</div></TabPane><TabPane tab="Leads" itemKey="leads">{rows(leads, "leads")}</TabPane><TabPane tab="Deals" itemKey="deals">{rows(deals, "deals")}</TabPane><TabPane tab="Products / Interests" itemKey="products"><div className="related-list">{products.map(({ product, count }) => <span key={product.id}>{product.name}<Tag size="small">{count} Deals</Tag></span>)}</div></TabPane><TabPane tab="Performance" itemKey="performance"><section className="data-panel"><PageHeader title="Performance" description="渠道转化与销售推进指标。" /><DataList rows={[["Lead → Deal", leads.length ? `${Math.round(leads.filter((lead) => lead.status === "CONVERTED").length / leads.length * 100)}%` : "0%"], ["Deal Win Rate", deals.length ? `${Math.round(deals.filter((deal) => deal.stage === "WON").length / deals.length * 100)}%` : "0%"]]} /></section></TabPane></Tabs>} sidebar={<SideSection title="Distributor"><DataList rows={[["Code", item.code], ["Country", item.country], ["Region", item.region], ["Manager", users.find((user) => user.role === "DISTRIBUTOR_MANAGER")?.name]]} /></SideSection>} />;
}

export function UsersPage() {
  const { state } = useCrm();
  const columns = [{ title: "User", dataIndex: "name", render: (_: unknown, user: (typeof state.users)[number]) => <TableEntity name={user.name} detail={user.email} /> }, { title: "Role", dataIndex: "role", render: (value: string) => <Tag>{value.replaceAll("_", " ")}</Tag> }, { title: "Title", dataIndex: "title" }, { title: "Distributor", dataIndex: "distributorId", render: (value: string) => state.distributors.find((item) => item.id === value)?.name }];
  return <div className="page"><PageHeader title="Users" description="Demo User 与角色范围。切换身份后，全应用数据范围同步变化。" /><section className="data-surface"><Table rowKey="id" columns={columns} dataSource={state.users} pagination={{ pageSize: 10 }} /></section></div>;
}
