import { useState } from "react";
import { Button, Input, Modal, Table, Tag, TextArea, Toast } from "@douyinfe/semi-ui";
import { IconPlus } from "@douyinfe/semi-icons";
import { DataList, DetailWorkspace, PageHeader, SideSection, StatusTag, TableEntity } from "@/components/CrmUi";
import { useCrm } from "@/stores/crm-store";
import type { Product, ProductCapability } from "@/types/crm";
import { navigate } from "@/utils/format";

export function ProductsPage({ id }: { id?: string }) { return id ? <ProductDetail id={id} /> : <ProductList />; }

function ProductList() {
  const { state, isHq, addProduct, updateProduct } = useCrm(); const [open, setOpen] = useState(false); const [form, setForm] = useState({ name: "", description: "" });
  const columns = [{ title: "Product", dataIndex: "name", width: 220, render: (_: unknown, product: Product) => <TableEntity name={product.name} detail={product.description} route={`products/${product.id}`} /> }, { title: "Status", dataIndex: "status", width: 100, render: (value: Product["status"]) => <StatusTag value={value} label={value} /> }, { title: "Add-ons", dataIndex: "capabilities", render: (values: ProductCapability[]) => <div className="tag-line">{values.map((item) => <Tag size="small" key={item.id}>{item.name}</Tag>)}</div> }, ...(isHq ? [{ title: "Actions", width: 120, render: (_: unknown, product: Product) => <Button size="small" type="tertiary" onClick={() => updateProduct(product.id, { status: product.status === "ACTIVE" ? "DISABLED" : "ACTIVE" })}>{product.status === "ACTIVE" ? "Disable" : "Enable"}</Button> }] : [])];
  return <div className="page"><PageHeader title="Products" description="Kivisense 产品与可组合 Add-ons 目录。" actions={isHq && <Button theme="solid" icon={<IconPlus />} onClick={() => setOpen(true)}>Create Product</Button>} /><section className="data-surface"><Table rowKey="id" columns={columns} dataSource={state.products} pagination={false} /></section><Modal visible={open} title="Create Product" onCancel={() => setOpen(false)} onOk={() => { if (!form.name) { Toast.warning("请输入产品名称"); return; } addProduct({ ...form, status: "ACTIVE", capabilities: [] }); setOpen(false); }}><div className="form-stack"><label>Name<Input value={form.name} onChange={(value) => setForm((current) => ({ ...current, name: value }))} /></label><label>Description<TextArea value={form.description} onChange={(value) => setForm((current) => ({ ...current, description: value }))} /></label></div></Modal></div>;
}

function ProductDetail({ id }: { id: string }) {
  const { state, isHq, updateProduct } = useCrm(); const product = state.products.find((item) => item.id === id); const [newCapability, setNewCapability] = useState(""); const [editOpen, setEditOpen] = useState(false); const [editForm, setEditForm] = useState({ name: "", description: "" });
  if (!product) return null;
  const addCapability = () => { if (!newCapability.trim()) return; updateProduct(product.id, { capabilities: [...product.capabilities, { id: `cap-${Date.now()}`, name: newCapability, description: `${newCapability} capability`, enabled: true }] }); setNewCapability(""); };
  const startEdit = () => { setEditForm({ name: product.name, description: product.description }); setEditOpen(true); };
  return <><DetailWorkspace eyebrow="Catalog / Products" title={product.name} subtitle={product.description} backRoute="products" tags={<StatusTag value={product.status} label={product.status} />} actions={isHq && <><Button onClick={startEdit}>Edit Product</Button><Button onClick={() => updateProduct(product.id, { status: product.status === "ACTIVE" ? "DISABLED" : "ACTIVE" })}>{product.status === "ACTIVE" ? "Disable Product" : "Enable Product"}</Button></>} tabs={<section className="data-panel"><PageHeader title="Add-ons" description="Distributor 只读；HQ 可以新增、启用或停用。" actions={isHq && <div className="inline-create"><Input aria-label="New Add-on" value={newCapability} onChange={setNewCapability} placeholder="New Add-on" /><Button icon={<IconPlus />} onClick={addCapability}>Add</Button></div>} /><div className="capability-grid">{product.capabilities.map((capability) => <article key={capability.id}><div><strong>{capability.name}</strong><p>{capability.description}</p></div><Tag color={capability.enabled ? "green" : "grey"}>{capability.enabled ? "Enabled" : "Disabled"}</Tag>{isHq && <Button size="small" onClick={() => updateProduct(product.id, { capabilities: product.capabilities.map((item) => item.id === capability.id ? { ...item, enabled: !item.enabled } : item) })}>{capability.enabled ? "Disable" : "Enable"}</Button>}</article>)}</div></section>} sidebar={<SideSection title="Product"><DataList rows={[["Name", product.name], ["Status", product.status], ["Add-ons", product.capabilities.length], ["Used by Deals", state.deals.filter((deal) => deal.productId === product.id).length]]} /></SideSection>} /><Modal visible={editOpen} title="Edit Product" onCancel={() => setEditOpen(false)} onOk={() => { if (!editForm.name.trim()) { Toast.warning("请输入产品名称"); return; } updateProduct(product.id, editForm); setEditOpen(false); }}><div className="form-stack"><label>Name<Input aria-label="Product Name" value={editForm.name} onChange={(value) => setEditForm((current) => ({ ...current, name: value }))} /></label><label>Description<TextArea aria-label="Product Description" value={editForm.description} onChange={(value) => setEditForm((current) => ({ ...current, description: value }))} /></label></div></Modal></>;
}
