import { useEffect, useId, useMemo, useState, type ReactNode } from "react";
import { Banner, Button, Empty, Input, InputNumber, Modal, Select, SideSheet, Switch, TabPane, Table, Tabs, Tag } from "@douyinfe/semi-ui";
import qrcode from "qrcode-generator";
import { DataList, DetailWorkspace, PageHeader, SideSection } from "@/components/CrmUi";
import { useCrm } from "@/stores/crm-store";
import { brandLabels, useMemberOperations } from "@/stores/member-operations-store";
import { useMarketing } from "@/stores/marketing-store";
import { createMarketingActivity, createMarketingSlot } from "@/mock/marketing-demo-data";
import type { MarketingActivity, MarketingAudit, MarketingAward, MarketingBooking, MarketingDraw, MarketingPoolItem, MarketingPrize, MarketingSlot } from "@/types/marketing";
import { navigate } from "@/utils/format";
import { parseCreatedAt, shanghaiDate } from "@/features/dashboard/dashboard-model";
import { activityMetrics, bookingLabels, bookingStatus, chances, claimLabels, drawBlock, marketingPermissions, marketingStatusLabels, participationFor, participationIssue, phase, quota, resolveCredential, slotFor, slotOccupancy, validateActivity, type MarketingCommand } from "./marketing-model";

const dateTime = (value: string) => Number.isFinite(parseCreatedAt(value)) ? new Date(parseCreatedAt(value) + 8 * 3_600_000).toISOString().slice(0, 16) : "";
const iso = (value: string) => value ? `${value}:00+08:00` : "";
const displayDate = (value?: string) => value && Number.isFinite(parseCreatedAt(value)) ? dateTime(value).replace("T", " ") : "未提供";
const uid = () => crypto.randomUUID();
const decodeCode = (value: string) => { try { return decodeURIComponent(value); } catch { return value; } };
const options = (labels: Record<string, string>) => Object.entries(labels).map(([value, label]) => ({ value, label }));
function SelectField({ label, value, list, onChange, disabled }: { label: string; value: string; list: { value: string; label: string }[]; onChange: (value: string) => void; disabled?: boolean }) { const id = useId(); return <label className="marketing-field"><span id={id}>{label}</span><Select aria-labelledby={id} value={value} optionList={list} onChange={(next) => onChange(String(next))} disabled={disabled} /></label>; }
function TextField({ label, value, onChange, type = "text", disabled }: { label: string; value: string; onChange: (value: string) => void; type?: string; disabled?: boolean }) { return <label className="marketing-field"><span>{label}</span><Input aria-label={label} type={type} value={value} onChange={onChange} disabled={disabled} /></label>; }
function NumberField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label className="marketing-field"><span>{label}</span><InputNumber aria-label={label} value={Number.isFinite(value) ? value : undefined} onChange={(next) => onChange(typeof next === "number" ? next : NaN)} /></label>; }
function TimeField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <TextField label={label} value={dateTime(value)} type="datetime-local" onChange={(next) => onChange(iso(next))} />; }
function Panel({ title, children, note }: { title: string; children: ReactNode; note?: string }) { return <section className="marketing-panel"><header><h2>{title}</h2>{note && <p>{note}</p>}</header><div>{children}</div></section>; }
function DemoNote() { return <p className="marketing-demo-note">纯前端演示 · 免费单人活动 · Asia/Shanghai（UTC+08）· 本地抽奖、容量和权限不具备生产并发安全或防作弊能力，不发送消息、不连接微信 / HQ。</p>; }
function Credential({ code, label }: { code: string; label: string }) { const data = useMemo(() => { const qr = qrcode(0, "M"); qr.addData(code); qr.make(); return qr.createDataURL(4, 16); }, [code]); return <div className="marketing-credential"><img src={data} alt={`${label}二维码`} /><div><strong>{label}</strong><code>{code}</code><small>仅含随机演示标识，不含手机号。核销工作台输入此码，或使用“模拟扫码”读取。</small><Button size="small" onClick={() => navigate(`marketing/redemption/${encodeURIComponent(code)}`)}>模拟扫码 / 输入核验</Button></div></div>; }
function ImageField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { const [error, setError] = useState(""); return <label className="marketing-field"><span>{label}（仅本地预览，不上传）</span><input aria-label={label} type="file" accept="image/*" onChange={(event) => { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith("image/") || file.size > 2_000_000) { setError("请选择不超过2MB的图片"); return; } const reader = new FileReader(); reader.onload = () => { onChange(String(reader.result)); setError(""); }; reader.readAsDataURL(file); }} />{value && <img className="marketing-cover" src={value} alt="本地演示封面" />}{error && <small>{error}</small>}</label>; }

export function MarketingPage({ path }: { path: string[] }) {
  const pathKey = path.join("/");
  useEffect(() => { void window.scrollTo(0, 0); }, [pathKey]);
  const { currentUser } = useCrm(), access = marketingPermissions(currentUser);
  const { state, issue, reset } = useMarketing();
  if (!access.brands.length) return <div className="page"><Banner type="warning" title="当前角色无权访问营销活动" description="营销品牌范围不会扩大销售分销商的会员数据权限。" closeIcon={null} /></div>;
  if (issue) return <div className="page"><Banner type="danger" title={issue} closeIcon={null} /><Button onClick={() => Modal.confirm({ title: "重置营销数据？", content: "只替换营销命名空间。销售与会员数据不变，请先备份无法读取的原内容。", onOk: reset })}>确认后重置营销数据</Button></div>;
  if (path[0] === "activity" || path[0] === "preview") {
    const activity = state.activities.find((row) => row.id === path[1] && access.brands.includes(row.brand));
    if (!activity) return <div className="page"><Empty title="活动不存在或无权访问" /></div>;
    return path[0] === "preview" ? <MarketingPreview key={`${activity.id}:${path[2] || ""}`} activity={activity} initialUserId={path[2]} /> : <MarketingDetail key={activity.id} activity={activity} />;
  }
  const tab = ["prizes", "bookings", "redemption"].includes(path[0]) ? path[0] : "activities";
  return <div className="page marketing-page"><Tabs activeKey={tab} onChange={(key) => navigate(key === "activities" ? "marketing" : `marketing/${key}`)}><TabPane itemKey="activities" tab="活动管理" /><TabPane itemKey="prizes" tab="奖品库" /><TabPane itemKey="bookings" tab="预约记录" /><TabPane itemKey="redemption" tab="核销工作台" /></Tabs><DemoNote />{tab === "activities" ? <MarketingList /> : tab === "prizes" ? <PrizeLibrary /> : tab === "bookings" ? <MarketingBookings /> : <RedemptionWorkbench key={path[1] || "input"} initialCode={path[1] ? decodeCode(path[1]) : ""} />}</div>;
}
function useAction() { const { act } = useMarketing(); const [message, setMessage] = useState(""); const run = (command: MarketingCommand) => { const result = act(command); setMessage(result.ok ? `操作已保存 · ${result.resultId || ""}` : result.error || "操作失败"); return result; }; return { run, message, feedback: message && <Banner type={message.startsWith("操作已保存") ? "success" : "warning"} title={message} closeIcon={null} /> }; }
function useAuthorizedActivities() { const { state } = useMarketing(), { currentUser } = useCrm(); return state.activities.filter((row) => marketingPermissions(currentUser).brands.includes(row.brand)); }
function ActivityPhases({ activity }: { activity: MarketingActivity }) { const now = Date.now(); return <div className="marketing-phases">{activity.bookingEnabled && <span>预约：{phase(now, activity.bookingStart, activity.bookingEnd)}</span>}<span>活动：{phase(now, activity.startAt, activity.endAt)}</span>{activity.lotteryEnabled && <span>抽奖：{phase(now, activity.lotteryStart, activity.lotteryEnd)}</span>}{activity.lotteryEnabled && <span>领奖：{activity.pool.some((item) => phase(now, item.claimStart, item.claimEnd) === "有效期内") ? "仍有有效权益期" : "无当前有效期"}</span>}</div>; }
function MarketingList() {
  const { state } = useMarketing(), { currentUser } = useCrm(), { state: members } = useMemberOperations(); const access = marketingPermissions(currentUser), activities = useAuthorizedActivities(), { run, feedback } = useAction();
  const [filters, setFilters] = useState({ search: "", brand: "ALL", status: "ALL", date: "" }); const [editing, setEditing] = useState<MarketingActivity | null>(null);
  const rows = activities.filter((row) => row.name.toLowerCase().includes(filters.search.toLowerCase()) && (filters.brand === "ALL" || row.brand === filters.brand) && (filters.status === "ALL" || row.status === filters.status) && (!filters.date || (parseCreatedAt(row.startAt) < parseCreatedAt(`${filters.date}T00:00:00+08:00`) + 86_400_000 && parseCreatedAt(row.endAt) >= parseCreatedAt(`${filters.date}T00:00:00+08:00`))));
  return <><PageHeader title="营销活动" description="配置与发布、参加活动、即时抽奖、中奖预约和履约共用同一份营销记录。" actions={<Button theme="solid" disabled={!access.manage || !members.brandUsers.length} title={!members.brandUsers.length ? "需要先建立授权品牌档案，营销模块不自动建会员" : undefined} onClick={() => setEditing(createMarketingActivity(access.brands[0], Date.now(), state.prizes))}>新建活动</Button>} />{!members.brandUsers.some((user) => access.brands.includes(user.brand) && user.is_deleted === 0) && <Banner type="warning" title="缺少可用品牌身份" description="需要先建立或核对授权品牌档案（含 is_deleted=0）；营销模块不会自动建会员或给旧数据补默认值。" closeIcon={null} />}{feedback}<div className="marketing-toolbar"><TextField label="搜索活动" value={filters.search} onChange={(search) => setFilters((old) => ({ ...old, search }))} /><SelectField label="活动品牌" value={filters.brand} list={[{ value: "ALL", label: "全部授权品牌" }, ...access.brands.map((brand) => ({ value: brand, label: brandLabels[brand] }))]} onChange={(brand) => setFilters((old) => ({ ...old, brand }))} /><SelectField label="发布状态" value={filters.status} list={[{ value: "ALL", label: "全部状态" }, ...options(marketingStatusLabels)]} onChange={(status) => setFilters((old) => ({ ...old, status }))} /><TextField label="活动举行日期" type="date" value={filters.date} onChange={(date) => setFilters((old) => ({ ...old, date }))} /></div>
    {rows.length ? <Table rowKey="id" dataSource={rows} pagination={{ pageSize: 10 }} scroll={{ x: 1160 }} columns={[{ title: "活动名称", width: 220, render: (_: unknown, row: MarketingActivity) => <a href={`#marketing/activity/${row.id}`}>{row.name}</a> }, { title: "品牌 / 形式", width: 140, render: (_: unknown, row: MarketingActivity) => `${row.brand} · ${row.mode === "OFFLINE" ? "线下" : "线上"}` }, { title: "活动日期", width: 190, render: (_: unknown, row: MarketingActivity) => <span>{displayDate(row.startAt)}<br />至 {displayDate(row.endAt)}</span> }, { title: "状态与独立时间阶段", width: 250, render: (_: unknown, row: MarketingActivity) => <><Tag size="small">{marketingStatusLabels[row.status]}</Tag><ActivityPhases activity={row} /></> }, { title: "能力", width: 100, render: (_: unknown, row: MarketingActivity) => `预约${row.bookingEnabled ? "开" : "关"} / 抽奖${row.lotteryEnabled ? "开" : "关"}` }, { title: "操作", width: 200, fixed: "right", render: (_: unknown, row: MarketingActivity) => <div className="button-row"><Button size="small" disabled={!access.manage} onClick={() => setEditing(structuredClone(row))}>编辑</Button><Button size="small" disabled={!access.manage || row.status === "CANCELED"} onClick={() => run({ type: "STATUS", activityId: row.id, status: row.status === "PUBLISHED" ? "PAUSED" : "PUBLISHED" })}>{row.status === "PUBLISHED" ? "暂停" : row.status === "PAUSED" ? "恢复" : "发布"}</Button></div> }]} /> : <Empty title="暂无匹配活动" description="调整筛选，或新建草稿活动。" />}
    {editing && <ActivityEditor key={editing.id} initial={editing} onClose={() => setEditing(null)} />}
  </>;
}
function SlotFields({ slot, onChange }: { slot: MarketingSlot; onChange: (slot: MarketingSlot) => void }) { const update = <K extends keyof MarketingSlot>(key: K, value: MarketingSlot[K]) => onChange({ ...slot, [key]: value }); return <div className="marketing-form-grid"><TextField label="场次名称" value={slot.label} onChange={(value) => update("label", value)} /><TextField label="场次地点" value={slot.location} onChange={(value) => update("location", value)} /><NumberField label="场次容量" value={slot.capacity} onChange={(value) => update("capacity", value)} />{(["startAt", "endAt", "bookingClosesAt", "checkinStart", "checkinEnd"] as const).map((key, index) => <TimeField key={key} label={["场次开始", "场次结束", "场次预约截止", "允许签到开始", "允许签到结束（含配置宽限）"][index]} value={slot[key]} onChange={(value) => update(key, value)} />)}</div>; }
function ActivityEditor({ initial, onClose }: { initial: MarketingActivity; onClose: () => void }) {
  const { state } = useMarketing(), { currentUser } = useCrm(), access = marketingPermissions(currentUser), { run, feedback } = useAction(); const [form, setForm] = useState(initial); const locked = Boolean(initial.publishedAt);
  const update = <K extends keyof MarketingActivity>(key: K, value: MarketingActivity[K]) => setForm((old) => ({ ...old, [key]: value }));
  const poolUpdate = (index: number, item: MarketingPoolItem) => update("pool", form.pool.map((old, n) => n === index ? item : old));
  const errors = validateActivity(form, state, access.brands);
  const save = (publish: boolean) => { const result = run({ type: "SAVE_ACTIVITY", activity: form }); if (!result.ok) return; if (publish && !run({ type: "STATUS", activityId: form.id, status: "PUBLISHED" }).ok) return; onClose(); navigate(`marketing/activity/${form.id}`); };
  return <SideSheet visible closeOnEsc width={Math.min(780, window.innerWidth - 20)} title={locked ? "编辑活动说明（规则已锁定）" : "新建 / 编辑活动"} onCancel={onClose} footer={<div className="button-row"><Button onClick={onClose}>取消</Button><Button onClick={() => save(false)}>{locked ? "保存说明" : "保存草稿"}</Button>{!locked && <Button theme="solid" onClick={() => save(true)}>保存并发布</Button>}</div>}><div className="marketing-editor"><DemoNote />{feedback}<Panel title="1 · 基本信息"><div className="marketing-form-grid"><TextField label="活动名称" value={form.name} onChange={(value) => update("name", value)} /><TextField label="活动说明" value={form.description} onChange={(value) => update("description", value)} /><ImageField label="活动封面" value={form.cover} onChange={(value) => update("cover", value)} /></div></Panel>
    {locked ? <Banner type="info" title="品牌、完成条件、次数、概率、中奖上限与场次锁定" description="仅可更新说明和封面。规则变化请复制为新活动；配额 / 履约时段在详情中有记录地追加。" closeIcon={null} /> : <>
      <Panel title="2 · 预约与完成规则"><div className="marketing-form-grid"><SelectField label="所属品牌" value={form.brand} list={access.brands.map((brand) => ({ value: brand, label: brandLabels[brand] }))} onChange={(value) => update("brand", value as MarketingActivity["brand"])} /><SelectField label="活动形式" value={form.mode} list={[{ value: "OFFLINE", label: "线下" }, { value: "ONLINE", label: "线上演示" }]} onChange={(value) => setForm((old) => ({ ...old, mode: value as MarketingActivity["mode"], completion: value === "ONLINE" ? "STAFF" : old.completion }))} />{form.mode === "OFFLINE" && <TextField label="线下地点" value={form.location} onChange={(value) => update("location", value)} />}<TimeField label="活动开始" value={form.startAt} onChange={(value) => update("startAt", value)} /><TimeField label="活动结束" value={form.endAt} onChange={(value) => update("endAt", value)} /><SelectField label="完成条件" value={form.completion} list={[{ value: "STAFF", label: "工作人员确认完成" }, ...(form.mode === "OFFLINE" ? [{ value: "CHECKIN", label: "到场签到即完成" }] : [])]} onChange={(value) => update("completion", value as MarketingActivity["completion"])} /><label>开启预约 <Switch aria-label="开启活动预约" checked={form.bookingEnabled} onChange={(value) => update("bookingEnabled", value)} /></label></div>
      {form.bookingEnabled && <><div className="marketing-form-grid"><TimeField label="预约开放" value={form.bookingStart} onChange={(value) => update("bookingStart", value)} /><TimeField label="预约截止" value={form.bookingEnd} onChange={(value) => update("bookingEnd", value)} /><label>允许现场报名 <Switch aria-label="允许现场报名" checked={form.allowWalkIn} onChange={(value) => update("allowWalkIn", value)} /></label></div>{form.slots.map((slot, index) => <details key={slot.id} open={index === 0}><summary>{slot.label}</summary><SlotFields slot={slot} onChange={(value) => update("slots", form.slots.map((old) => old.id === value.id ? value : old))} /><Button type="danger" size="small" onClick={() => update("slots", form.slots.filter((old) => old.id !== slot.id))}>删除草稿场次</Button></details>)}<Button size="small" onClick={() => update("slots", [...form.slots, createMarketingSlot(uid(), Date.now())])}>添加活动场次</Button></>}
      </Panel><Panel title="3 · 抽奖与奖池"><label>开启即时抽奖 <Switch aria-label="开启活动抽奖" checked={form.lotteryEnabled} onChange={(value) => update("lotteryEnabled", value)} /></label>{form.lotteryEnabled && <><div className="marketing-form-grid"><TimeField label="抽奖开始" value={form.lotteryStart} onChange={(value) => update("lotteryStart", value)} /><TimeField label="抽奖截止" value={form.lotteryEnd} onChange={(value) => update("lotteryEnd", value)} />{(["grantCount", "drawLimit", "winLimit", "noWinProbability"] as const).map((key, index) => <NumberField key={key} label={["首次完成发放次数", "活动累计抽奖上限", "累计中奖上限", "未中奖概率（%）"][index]} value={form[key]} onChange={(value) => update(key, value)} />)}<label>启用每日上限 <Switch aria-label="启用每日抽奖上限" checked={form.dailyLimit !== null} onChange={(value) => update("dailyLimit", value ? 1 : null)} /></label>{form.dailyLimit !== null && <NumberField label="每日抽奖上限" value={form.dailyLimit} onChange={(value) => update("dailyLimit", value)} />}</div>
        {form.pool.map((item, index) => <details key={item.id} open={index === 0}><summary>{item.label}</summary><div className="marketing-form-grid"><SelectField label="引用奖品" value={item.prizeId} list={state.prizes.map((prize) => ({ value: prize.id, label: prize.name }))} onChange={(value) => { const prize = state.prizes.find((row) => row.id === value)!; poolUpdate(index, { ...item, prizeId: value, label: prize.name, method: prize.method, slots: prize.method === "DIRECT" ? [] : item.slots.length ? item.slots : [createMarketingSlot(uid(), Date.now(), item.quota)] }); }} /><TextField label="本活动奖项名称" value={item.label} onChange={(value) => poolUpdate(index, { ...item, label: value })} /><NumberField label="本活动配额" value={item.quota} onChange={(value) => poolUpdate(index, { ...item, quota: value })} /><NumberField label="中奖概率（%）" value={item.probability} onChange={(value) => poolUpdate(index, { ...item, probability: value })} /><NumberField label="每人该奖品中奖上限" value={item.perPersonLimit} onChange={(value) => poolUpdate(index, { ...item, perPersonLimit: value })} /><SelectField label="领取方式" value={item.method} list={options(claimLabels)} onChange={(value) => poolUpdate(index, { ...item, method: value as MarketingPoolItem["method"], slots: value === "DIRECT" ? [] : item.slots.length ? item.slots : [createMarketingSlot(uid(), Date.now(), item.quota)] })} /><TextField label="奖品领取地点" value={item.location} onChange={(value) => poolUpdate(index, { ...item, location: value })} /><TextField label="领取说明" value={item.instructions} onChange={(value) => poolUpdate(index, { ...item, instructions: value })} /><TimeField label="奖品有效开始" value={item.claimStart} onChange={(value) => poolUpdate(index, { ...item, claimStart: value })} /><TimeField label="奖品有效截止" value={item.claimEnd} onChange={(value) => poolUpdate(index, { ...item, claimEnd: value })} /></div>{item.method !== "DIRECT" && <>{item.slots.map((slot) => <SlotFields key={slot.id} slot={slot} onChange={(value) => poolUpdate(index, { ...item, slots: item.slots.map((old) => old.id === value.id ? value : old) })} />)}<Button size="small" onClick={() => poolUpdate(index, { ...item, slots: [...item.slots, createMarketingSlot(uid(), Date.now())] })}>添加履约时段</Button></>}<Button type="danger" size="small" onClick={() => update("pool", form.pool.filter((old) => old.id !== item.id))}>删除草稿奖池项</Button></details>)}<Button size="small" onClick={() => { const prize = state.prizes.find((row) => !form.pool.some((item) => item.prizeId === row.id)); if (!prize) return; update("pool", [...form.pool, { id: uid(), prizeId: prize.id, label: prize.name, quota: 1, probability: 0, perPersonLimit: 1, method: prize.method, location: form.location, instructions: "凭中奖码履约", claimStart: form.startAt, claimEnd: form.lotteryEnd, slots: prize.method === "DIRECT" ? [] : [createMarketingSlot(uid(), Date.now())] }]); }} disabled={state.prizes.every((prize) => form.pool.some((item) => item.prizeId === prize.id))}>添加未选奖品（可先扩充奖品库）</Button>
      </>}</Panel><Panel title="4 · 发布检查" note="保存草稿可保留不完整配置；发布必须全部通过。">{errors.length ? <ul>{errors.map((error) => <li key={error}>{error}</li>)}</ul> : <p>配置检查通过，等待发布。</p>}<p>固定概率：库存耗尽 / 个人奖品上限对应概率转为未中奖，不重新分配。抽奖在完成后由用户即时发起。</p></Panel>
    </>}
  </div></SideSheet>;
}
function PrizeLibrary() {
  const { state } = useMarketing(), { run, feedback } = useAction(); const [edit, setEdit] = useState<MarketingPrize | null>(null);
  return <><PageHeader title="奖品库" description="仅复用定义；配额按活动隔离，修改定义不覆盖已中奖承诺。" actions={<Button onClick={() => setEdit({ id: uid(), name: "", description: "", image: "", method: "DIRECT" })}>新增奖品</Button>} />{feedback}<Table rowKey="id" dataSource={state.prizes} pagination={{ pageSize: 10 }} scroll={{ x: 650 }} columns={[{ title: "奖品", dataIndex: "name" }, { title: "说明", dataIndex: "description" }, { title: "默认领取方式", render: (_: unknown, row: MarketingPrize) => claimLabels[row.method] }, { title: "操作", render: (_: unknown, row: MarketingPrize) => <div className="button-row"><Button size="small" onClick={() => setEdit(structuredClone(row))}>编辑</Button><Button type="danger" size="small" disabled={state.activities.some((activity) => activity.pool.some((item) => item.prizeId === row.id))} onClick={() => run({ type: "DELETE_PRIZE", prizeId: row.id })}>删除</Button></div> }]} />{edit && <Modal visible title="奖品定义（本地演示）" onCancel={() => setEdit(null)} onOk={() => { if (run({ type: "SAVE_PRIZE", prize: edit }).ok) setEdit(null); }}>{feedback}<TextField label="奖品名称" value={edit.name} onChange={(name) => setEdit({ ...edit, name })} /><TextField label="奖品说明" value={edit.description} onChange={(description) => setEdit({ ...edit, description })} /><SelectField label="默认领取方式" value={edit.method} list={options(claimLabels)} onChange={(method) => setEdit({ ...edit, method: method as MarketingPrize["method"] })} /><ImageField label="奖品图片" value={edit.image} onChange={(image) => setEdit({ ...edit, image })} /></Modal>}</>;
}
function BookingTable({ rows }: { rows: MarketingBooking[] }) {
  const { state } = useMarketing(), { run, feedback } = useAction(); const [change, setChange] = useState<MarketingBooking | null>(null), [target, setTarget] = useState("");
  const activity = state.activities.find((row) => row.id === change?.activityId), slots = change?.kind === "ACTIVITY" ? activity?.slots : activity?.pool.find((item) => item.id === change?.poolItemId)?.slots;
  return <>{feedback}{rows.length ? <Table rowKey="id" dataSource={rows} pagination={{ pageSize: 10 }} scroll={{ x: 920 }} columns={[{ title: "预约类型 / 活动", width: 250, render: (_: unknown, row: MarketingBooking) => <span>{row.kind === "ACTIVITY" ? "参加活动" : "中奖履约"} · <a href={`#marketing/activity/${row.activityId}`}>{state.activities.find((activity) => activity.id === row.activityId)?.name}</a></span> }, { title: "参与主体", dataIndex: "participationId", width: 210 }, { title: "场次", width: 200, render: (_: unknown, row: MarketingBooking) => `${slotFor(state, row)?.label || "场次待核对"} · ${displayDate(slotFor(state, row)?.startAt)}` }, { title: "当前状态", width: 100, render: (_: unknown, row: MarketingBooking) => bookingLabels[bookingStatus(row, slotFor(state, row), Date.now())] }, { title: "操作", width: 160, fixed: "right", render: (_: unknown, row: MarketingBooking) => <div className="button-row"><Button size="small" disabled={row.status !== "BOOKED"} onClick={() => { setChange(row); setTarget(row.slotId); }}>改约</Button><Button size="small" disabled={row.status !== "BOOKED"} onClick={() => run({ type: "CANCEL_BOOKING", bookingId: row.id })}>取消预约</Button></div> }]} /> : <Empty title="暂无当前范围预约" description="活动与奖品预约来自同一数据源，业务类型独立。" />}{change && <Modal visible title="改约（失败保留原预约）" onCancel={() => setChange(null)} onOk={() => { if (run({ type: "RESCHEDULE", bookingId: change.id, slotId: target }).ok) setChange(null); }}>{feedback}<SelectField label="目标场次" value={target} list={(slots || []).map((slot) => ({ value: slot.id, label: `${slot.label} · ${displayDate(slot.startAt)}` }))} onChange={setTarget} /></Modal>}</>;
}
function MarketingBookings() { const activities = useAuthorizedActivities(), { state } = useMarketing(); const [kind, setKind] = useState("ALL"), [activityId, setActivityId] = useState("ALL"); const rows = state.bookings.filter((row) => activities.some((activity) => activity.id === row.activityId) && (kind === "ALL" || row.kind === kind) && (activityId === "ALL" || row.activityId === activityId)); return <><PageHeader title="预约记录" description="活动预约解决到场容量；奖品预约解决中奖履约，不互相替代。" /><div className="marketing-toolbar"><SelectField label="预约业务类型" value={kind} onChange={setKind} list={[{ value: "ALL", label: "全部类型" }, { value: "ACTIVITY", label: "参加活动" }, { value: "PRIZE", label: "中奖履约" }]} /><SelectField label="预约所属活动" value={activityId} onChange={setActivityId} list={[{ value: "ALL", label: "全部授权活动" }, ...activities.map((row) => ({ value: row.id, label: row.name }))]} /></div><BookingTable rows={rows} /></>; }
function MarketingDetail({ activity }: { activity: MarketingActivity }) {
  const { state, reset } = useMarketing(), { run, feedback } = useAction(); const [tab, setTab] = useState("overview"), [edit, setEdit] = useState(false), [detail, setDetail] = useState<{ title: string; rows: { id: string }[] } | null>(null), [extra, setExtra] = useState({ itemId: "", count: 1 });
  const [addingSlot, setAddingSlot] = useState<{ itemId: string; slot: MarketingSlot } | null>(null);
  const snapshotNow = useMemo(() => Date.now(), [state, activity.id]);
  useEffect(() => setDetail(null), [state, activity.id]);
  const metrics = activityMetrics(state, activity, snapshotNow), participants = state.participations.filter((row) => row.activityId === activity.id), awards = state.awards.filter((row) => row.activityId === activity.id), audits = state.audits.filter((row) => row.activityId === activity.id).reverse();
  const cancel = () => Modal.confirm({ title: "取消活动？", content: `${state.bookings.filter((row) => row.activityId === activity.id && row.kind === "ACTIVITY" && row.status === "BOOKED").length} 条未到场活动预约将取消；保留 ${awards.length} 份获奖权益及既有奖品预约，已发生记录不抹掉。`, onOk: () => { run({ type: "STATUS", activityId: activity.id, status: "CANCELED" }); } });
  return <><DetailWorkspace eyebrow="会员与品牌运营 / 营销活动" title={activity.name} subtitle={`${brandLabels[activity.brand]} · ${activity.mode === "OFFLINE" ? "线下" : "线上"} · 免费活动`} backRoute="marketing" tags={<Tag>{marketingStatusLabels[activity.status]}</Tag>} actions={<><Button onClick={() => setEdit(true)}>编辑配置</Button><Button onClick={() => navigate(`marketing/preview/${activity.id}`)}>用户流程预览</Button><Button onClick={() => { const result = run({ type: "COPY_ACTIVITY", activityId: activity.id }); if (result.ok) navigate(`marketing/activity/${result.resultId}`); }}>复制新活动</Button>{activity.status !== "CANCELED" && <Button onClick={() => run({ type: "STATUS", activityId: activity.id, status: activity.status === "PUBLISHED" ? "PAUSED" : "PUBLISHED" })}>{activity.status === "PUBLISHED" ? "暂停" : activity.status === "PAUSED" ? "恢复" : "发布"}</Button>}<Button type="danger" disabled={activity.status === "CANCELED"} onClick={cancel}>取消活动</Button>{!activity.publishedAt && !participants.length && <Button type="danger" onClick={() => { if (run({ type: "DELETE_ACTIVITY", activityId: activity.id }).ok) navigate("marketing"); }}>删除无记录草稿</Button>}</>} sidebar={<><SideSection title="独立时间阶段"><ActivityPhases activity={activity} /><DataList rows={[["活动期", `${displayDate(activity.startAt)} 至 ${displayDate(activity.endAt)}`], ["抽奖截止", activity.lotteryEnabled ? displayDate(activity.lotteryEnd) : "未开启"], ["规则版本", activity.ruleVersion]]} /></SideSection><SideSection title="原型边界"><DemoNote /><p>没有统一审计模块；此处保存本模块操作人、对象、真实发生时间与结果。未改会员旅程。</p><Button size="small" onClick={() => Modal.confirm({ title: "重置营销数据？", content: "仅恢复营销演示，销售与会员数据不变。", onOk: reset })}>重置营销演示数据</Button></SideSection></>} tabs={<><DemoNote />{feedback}<Tabs activeKey={tab} onChange={setTab}><TabPane itemKey="overview" tab="概览"><Panel title="活动核心指标" note={`截至 ${displayDate(new Date(snapshotNow).toISOString())}；人数按参与主体去重，次数按业务记录。点击同口径明细。`}><div className="marketing-metrics">{metrics.slice(0, 3).map((metric) => <button key={metric.label} onClick={() => setDetail({ title: `${metric.label} · ${metric.kind}`, rows: metric.rows })}><span>{metric.label}</span><strong>{metric.rows.length}</strong></button>)}</div></Panel><Panel title="抽奖与履约明细指标"><div className="marketing-metrics">{metrics.slice(3).map((metric) => <button key={metric.label} onClick={() => setDetail({ title: `${metric.label} · ${metric.kind}`, rows: metric.rows })}><span>{metric.label}</span><strong>{metric.rows.length}</strong><small>{metric.kind}</small></button>)}</div></Panel></TabPane>
      <TabPane itemKey="config" tab="活动配置"><Panel title="配置摘要"><DataList rows={[["说明", activity.description], ["品牌", brandLabels[activity.brand]], ["预约", activity.bookingEnabled ? "开启" : "关闭"], ["现场报名", activity.allowWalkIn ? "允许（仍验证容量）" : "不允许"], ["抽奖", activity.lotteryEnabled ? "用户完成后即时抽奖" : "关闭"], ["完成条件", activity.completion === "CHECKIN" ? "线下到场即完成" : "工作人员确认完成"], ["发放 / 上限", activity.lotteryEnabled ? `首次完成发放 ${activity.grantCount} 次，活动抽奖上限 ${activity.drawLimit}，累计中奖上限 ${activity.winLimit}` : "未开启"], ["概率规则", "库存 / 个别奖品限额不可用时，概率转入未中奖；无有效可中奖概率则停抽，不扣次。"]]} />{activity.cover && <img className="marketing-cover" src={activity.cover} alt="本地活动封面" />}</Panel></TabPane>
      <TabPane itemKey="bookings" tab="场次与预约"><Panel title="活动场次">{activity.bookingEnabled ? activity.slots.map((slot) => <p key={slot.id}>{slot.label} · {displayDate(slot.startAt)} · {slot.location} · 已占 {slotOccupancy(state, activity.id, "ACTIVITY", slot.id)} / {slot.capacity} · 截止 {displayDate(slot.bookingClosesAt)}</p>) : <p>未开启活动预约，不要求虚构场次。</p>}</Panel><BookingTable rows={state.bookings.filter((row) => row.activityId === activity.id)} /></TabPane>
      <TabPane itemKey="participants" tab="参与名单"><ParticipantTable activity={activity} /></TabPane>
      <TabPane itemKey="lottery" tab="抽奖与奖品">{activity.lotteryEnabled ? <><Panel title="本活动奖池" note="总配额 = 待履约占用 + 已发放 + 可抽；过期未领不返池。"><Table rowKey="id" dataSource={activity.pool} pagination={false} scroll={{ x: 760 }} columns={[{ title: "奖项 / 领取方式", width: 220, render: (_: unknown, item: MarketingPoolItem) => `${item.label} / ${claimLabels[item.method]}` }, { title: "概率", render: (_: unknown, item: MarketingPoolItem) => `${item.probability}%` }, { title: "总配额 / 占用 / 发放 / 可抽", width: 210, render: (_: unknown, item: MarketingPoolItem) => { const q = quota(state, activity.id, item); return `${q.total} / ${q.held} / ${q.issued} / ${q.available}`; } }, { title: "有记录地追加", width: 220, render: (_: unknown, item: MarketingPoolItem) => <div className="button-row"><Button size="small" onClick={() => setExtra({ itemId: item.id, count: 1 })}>增加配额</Button>{item.method !== "DIRECT" && <Button size="small" onClick={() => setAddingSlot({ itemId: item.id, slot: createMarketingSlot(uid(), Date.now()) })}>追加履约时段</Button>}</div> }]} /></Panel><AwardTable rows={awards} /><Panel title="全部抽奖结果（含未中奖）"><Table rowKey="id" dataSource={state.draws.filter((row) => row.activityId === activity.id)} scroll={{ x: 650 }} columns={[{ title: "操作标识", dataIndex: "operationId" }, { title: "参与主体", dataIndex: "participationId" }, { title: "结果", render: (_: unknown, row: MarketingDraw) => row.poolItemId ? activity.pool.find((item) => item.id === row.poolItemId)?.label || "历史奖项快照见获奖权益" : "未中奖" }, { title: "发生时间（UTC+08）", render: (_: unknown, row: MarketingDraw) => displayDate(row.occurredAt) }]} /></Panel></> : <Empty title="本活动未开启抽奖" description="仍可报名、签到、完成确认并统计。" />}</TabPane>
      <TabPane itemKey="audit" tab="核销记录"><Panel title="本模块操作记录（含拒绝）"><Table rowKey="id" dataSource={audits} scroll={{ x: 760 }} columns={[{ title: "动作", dataIndex: "action" }, { title: "对象", dataIndex: "targetId" }, { title: "操作人", dataIndex: "actorId" }, { title: "发生时间（UTC+08）", render: (_: unknown, row: MarketingAudit) => displayDate(row.occurredAt) }, { title: "结果", dataIndex: "result" }, { title: "说明", dataIndex: "detail" }]} /></Panel></TabPane>
    </Tabs></>} />{edit && <ActivityEditor initial={structuredClone(activity)} onClose={() => setEdit(false)} />}
    <SideSheet visible={Boolean(detail)} closeOnEsc onCancel={() => setDetail(null)} title={detail?.title} width={Math.min(600, window.innerWidth - 20)}><p>本活动 · {brandLabels[activity.brand]} · 当前授权范围 · 截至 {displayDate(new Date(snapshotNow).toISOString())} · 同口径只读记录</p>{detail?.rows.length ? <Table rowKey="id" dataSource={detail.rows} columns={[{ title: "记录 ID", dataIndex: "id" }]} /> : <Empty title="当前口径暂无记录" />}</SideSheet>
    <Modal visible={Boolean(extra.itemId)} title="增加活动配额（不削减库存）" onCancel={() => setExtra({ itemId: "", count: 1 })} onOk={() => { if (run({ type: "ADD_QUOTA", activityId: activity.id, poolItemId: extra.itemId, count: extra.count }).ok) setExtra({ itemId: "", count: 1 }); }}>{feedback}<NumberField label="追加配额" value={extra.count} onChange={(count) => setExtra({ ...extra, count })} /></Modal>
    <Modal visible={Boolean(addingSlot)} title="追加履约时段" onCancel={() => setAddingSlot(null)} onOk={() => { if (addingSlot && run({ type: "ADD_PRIZE_SLOT", activityId: activity.id, poolItemId: addingSlot.itemId, slot: addingSlot.slot }).ok) setAddingSlot(null); }}>{feedback}{addingSlot && <SlotFields slot={addingSlot.slot} onChange={(slot) => setAddingSlot({ ...addingSlot, slot })} />}</Modal>
  </>;
}
function ParticipantTable({ activity }: { activity: MarketingActivity }) { const { state } = useMarketing(), { state: members } = useMemberOperations(); return <Table rowKey="id" dataSource={state.participations.filter((row) => row.activityId === activity.id)} scroll={{ x: 950 }} columns={[{ title: "参与主体 / 现有品牌档案", width: 260, render: (_: unknown, row: typeof state.participations[number]) => <span>{row.subjectKey}<br />{row.identities.map((ref) => ref.userId).join(" · ")}{participationIssue(row, members) && <small> · 身份引用待核对</small>}</span> }, { title: "报名 / 到场 / 完成", width: 260, render: (_: unknown, row: typeof state.participations[number]) => `${displayDate(row.registeredAt)} / ${displayDate(row.checkedInAt)} / ${displayDate(row.completedAt)}` }, { title: "获得 / 已用 / 剩余", width: 150, render: (_: unknown, row: typeof state.participations[number]) => { const c = chances(state, row); return `${c.earned} / ${c.used} / ${c.remaining}`; } }, { title: "活动凭证", width: 280, render: (_: unknown, row: typeof state.participations[number]) => <a href={`#marketing/redemption/${encodeURIComponent(row.credential)}`}>{row.credential}</a> }]} />; }
function AwardTable({ rows }: { rows: MarketingAward[] }) { return rows.length ? <Table rowKey="id" dataSource={rows} scroll={{ x: 800 }} columns={[{ title: "获奖权益快照", dataIndex: "prizeName", width: 200 }, { title: "领取方式", width: 130, render: (_: unknown, row: MarketingAward) => claimLabels[row.method] }, { title: "当前状态", width: 160, render: (_: unknown, row: MarketingAward) => row.fulfilledAt ? `已履约 · ${displayDate(row.fulfilledAt)}` : Date.now() >= parseCreatedAt(row.claimEnd) ? "已过期（仍占配额）" : "待履约" }, { title: "领奖凭证", width: 290, render: (_: unknown, row: MarketingAward) => <a href={`#marketing/redemption/${encodeURIComponent(row.credential)}`}>{row.credential}</a> }]} /> : <Empty title="暂无获奖权益" />; }

function MarketingPreview({ activity, initialUserId }: { activity: MarketingActivity; initialUserId?: string }) {
  const { state } = useMarketing(), { currentUser } = useCrm(), { state: members } = useMemberOperations(), { run, feedback } = useAction(); const users = members.brandUsers.filter((row) => row.brand === activity.brand && row.is_deleted === 0 && marketingPermissions(currentUser).brands.includes(row.brand));
  const [userId, setUserId] = useState(initialUserId || users[0]?.id || ""), [slotId, setSlotId] = useState(activity.slots[0]?.id || ""), [prizeSlots, setPrizeSlots] = useState<Record<string, string>>({}), [drawing, setDrawing] = useState(false);
  const identity = participationFor(state, activity, members, userId), row = identity.participation;
  const ctx = { actor: currentUser, members, now: Date.now() }; const reason = identity.error || drawBlock(state, activity, row, ctx), balance = row ? chances(state, row) : { earned: 0, used: 0, remaining: 0 };
  const draws = state.draws.filter((draw) => draw.participationId === row?.id), last = draws.at(-1), awards = state.awards.filter((award) => award.participationId === row?.id);
  const bookings = state.bookings.filter((booking) => booking.participationId === row?.id);
  return <div className="page marketing-preview"><Button theme="borderless" onClick={() => navigate(`marketing/activity/${activity.id}`)}>返回活动后台</Button><PageHeader title="用户流程预览" description={`${activity.name} · ${brandLabels[activity.brand]} · 非真实小程序`} /><DemoNote /><SelectField label="预览现有品牌用户" value={userId} onChange={setUserId} list={users.map((user) => ({ value: user.id, label: user.id }))} />{!users.length && <Banner type="warning" title="当前品牌没有已确认有效的会员身份" description="请先核对品牌档案；不在营销 Store 创建会员。" closeIcon={null} />}{feedback}{identity.error ? <Banner type="warning" title={identity.error} closeIcon={null} /> : <>
    <Panel title="1 · 参加活动" note="预约只占名额，不代表完成，也不发抽奖次数。"><ActivityPhases activity={activity} /><p>{activity.description}</p>{activity.bookingEnabled && <SelectField label="参加活动场次" value={slotId} onChange={setSlotId} list={activity.slots.map((slot) => ({ value: slot.id, label: `${slot.label} · ${displayDate(slot.startAt)} · 剩余 ${Math.max(0, slot.capacity - slotOccupancy(state, activity.id, "ACTIVITY", slot.id))}` }))} />}<div className="button-row"><Button theme="solid" disabled={activity.status !== "PUBLISHED" || !userId} onClick={() => run({ type: "REGISTER", activityId: activity.id, userId, slotId: activity.bookingEnabled ? slotId : undefined })}>{activity.bookingEnabled ? "预约参加" : "直接报名参加"}</Button>{activity.bookingEnabled && activity.allowWalkIn && <Button disabled={activity.status !== "PUBLISHED"} onClick={() => run({ type: "REGISTER", activityId: activity.id, userId, slotId, walkIn: true })}>工作人员现场报名（验容量）</Button>}</div>{row && <><p>参与状态：{row.completedAt ? "已完成" : row.checkedInAt ? "已签到 / 参与中" : "已报名 / 待到场"}</p><Credential code={row.credential} label="活动凭证（签到 / 完成）" /></>}</Panel>
    <Panel title="我的预约"><BookingTable rows={bookings} /></Panel>
    {activity.lotteryEnabled && <Panel title="2 · 完成后即时抽奖" note="累计获得、已用与剩余不是配置上限。库存或个人限额不可用的奖品概率转入未中奖。"><DataList rows={[["累计获得", String(balance.earned)], ["已使用", String(balance.used)], ["剩余", String(balance.remaining)], ["活动抽奖上限", activity.drawLimit], ["不可使用原因", reason || "可抽奖"]]} /><div className="button-row"><Button theme="solid" loading={drawing} disabled={Boolean(reason) || drawing} onClick={async () => { setDrawing(true); await Promise.resolve(); run({ type: "DRAW", activityId: activity.id, userId, operationId: uid() }); setDrawing(false); }}>即时抽奖</Button>{last && <Button onClick={() => run({ type: "DRAW", activityId: activity.id, userId, operationId: last.operationId })}>重试上次请求（返回原结果）</Button>}</div>{last && <p className="marketing-draw-result" role="status">最近已保存结果：{last.poolItemId ? state.awards.find((award) => award.drawId === last.id)?.prizeName : "未中奖"} · 结果ID {last.id}</p>}</Panel>}
    <Panel title="3 · 我的奖品 / 履约" note="中奖已经占用配额。预约不重报名、不再扣抽奖机会；过期不自动返池。">{awards.length ? awards.map((award) => { const item = activity.pool.find((pool) => pool.id === award.poolItemId); const active = bookings.find((booking) => booking.awardId === award.id && ["BOOKED", "FULFILLED"].includes(booking.status)); return <section className="marketing-my-award" key={award.id}><h3>{award.prizeName}</h3><p>{claimLabels[award.method]} · {award.fulfilledAt ? "已履约" : Date.now() >= parseCreatedAt(award.claimEnd) ? "已过期，不能领取" : "待履约"}</p><p>承诺快照：{award.instructions} · 截止 {displayDate(award.claimEnd)} · 规则 v{award.ruleVersion}</p>{award.method !== "DIRECT" && !award.fulfilledAt && <><SelectField label={`奖品预约时段 ${award.id}`} value={prizeSlots[award.id] || item?.slots[0]?.id || ""} onChange={(value) => setPrizeSlots((old) => ({ ...old, [award.id]: value }))} list={(item?.slots || []).map((slot) => ({ value: slot.id, label: `${slot.label} · ${displayDate(slot.startAt)} · 剩余 ${Math.max(0, slot.capacity - slotOccupancy(state, activity.id, "PRIZE", slot.id, item?.id))}` }))} /><Button disabled={Boolean(active) || Date.now() >= parseCreatedAt(award.claimEnd)} onClick={() => run({ type: "BOOK_PRIZE", awardId: award.id, slotId: prizeSlots[award.id] || item?.slots[0]?.id || "" })}>预约奖品领取 / 体验</Button></>}<Credential code={award.credential} label="奖品凭证（具体获奖权益）" /></section>; }) : <Empty title="暂无获奖权益" description="未中奖也是已保存的有效抽奖结果。" />}</Panel>
  </>}</div>;
}

function RedemptionWorkbench({ initialCode = "" }: { initialCode?: string }) {
  const { state } = useMarketing(), { currentUser } = useCrm(), { state: members } = useMemberOperations(), { run, feedback } = useAction(); const [code, setCode] = useState(initialCode), [recognized, setRecognized] = useState(""), [action, setAction] = useState("CHECKIN"), [location, setLocation] = useState(""), [slotId, setSlotId] = useState("");
  const ctx = { actor: currentUser, members, now: Date.now() }, token = recognized ? resolveCredential(state, recognized, ctx) : null;
  const booking = state.bookings.find((row) => token?.award ? row.awardId === token.award.id && row.status === "BOOKED" : row.participationId === token?.participation?.id && row.kind === "ACTIVITY" && ["BOOKED", "CHECKED_IN"].includes(row.status));
  const slot = booking && slotFor(state, booking);
  const recognize = () => { setRecognized(code.trim()); const result = resolveCredential(state, code.trim(), ctx); const matched = state.bookings.find((row) => result.award ? row.awardId === result.award.id && row.status === "BOOKED" : row.participationId === result.participation?.id && row.kind === "ACTIVITY" && ["BOOKED", "CHECKED_IN"].includes(row.status)); const matchedSlot = matched && slotFor(state, matched); setAction(result.award ? "CLAIM" : result.participation?.checkedInAt ? "COMPLETE" : "CHECKIN"); setLocation(matchedSlot?.location ?? result.award?.location ?? result.activity?.location ?? ""); setSlotId(matchedSlot?.id ?? ""); };
  return <div className="marketing-redemption"><PageHeader title="核销工作台" description="活动签到、完成确认与奖品核销分别执行；先识别再明确确认。" /><DemoNote /><div className="marketing-toolbar"><TextField label="演示凭证码" value={code} onChange={(value) => { setCode(value); setRecognized(""); }} /><Button theme="solid" onClick={recognize}>识别凭证 / 模拟扫码</Button></div>{feedback}{token?.error && <Banner type="warning" title={token.error} closeIcon={null} />}{token?.activity && token.participation && <Panel title="核验后确认" note="未到窗口、已取消、过期、类型 / 品牌 / 地点不符都会拒绝，不模拟成功。"><DataList rows={[["凭证类型", token.award ? "具体获奖权益" : "活动参与"], ["活动", token.activity.name], ["品牌", brandLabels[token.activity.brand]], ["用户引用", token.participation.identities.map((row) => row.userId).join(" · ")], ["奖品 / 当前状态", token.award ? `${token.award.prizeName} · ${token.award.fulfilledAt ? "已履约" : phase(Date.now(), token.award.claimStart, token.award.claimEnd)}` : token.participation.completedAt ? "已完成" : token.participation.checkedInAt ? "已签到 / 参与中" : "待到场"], ["预约场次", slot ? `${slot.label} · ${displayDate(slot.startAt)} · ${bookingLabels[bookingStatus(booking!, slot, Date.now())]}` : "没有有效预约"], ["允许窗口", slot ? `${displayDate(slot.checkinStart)} 至 ${displayDate(slot.checkinEnd)}` : "按活动 / 奖品有效期"]]} /><div className="marketing-form-grid"><SelectField label="本次核验动作" value={action} onChange={setAction} list={[{ value: "CHECKIN", label: "活动签到（不默认完成）" }, { value: "COMPLETE", label: "工作人员确认完成（不默认领奖）" }, { value: "CLAIM", label: "奖品领取 / 体验核销" }]} /><TextField label="当前核验地点" value={location} onChange={setLocation} /><TextField label="本次场次标识" value={slotId} onChange={setSlotId} /></div><Button theme="solid" onClick={() => Modal.confirm({ title: "确认执行核验？", content: `${options({ CHECKIN: "活动签到", COMPLETE: "完成确认", CLAIM: "奖品核销" }).find((row) => row.value === action)?.label} · ${token.activity!.name} · ${location}，会按当前真实状态验证。`, onOk: () => { run({ type: "VERIFY", credential: recognized, action: action as "CHECKIN" | "COMPLETE" | "CLAIM", location, slotId }); } })}>确认执行所选动作</Button></Panel>}{!recognized && <Empty title="请输入或从用户预览带入凭证码" description="二维码编码同一个可核验演示标识；没有摄像头时使用输入 / 模拟扫码。" />}</div>;
}
export function MemberMarketingRecords({ userId }: { userId: string }) {
  const { state } = useMarketing(), { currentUser } = useCrm(), { state: members } = useMemberOperations(); const user = members.brandUsers.find((row) => row.id === userId), brands = marketingPermissions(currentUser).brands;
  if (!user || !brands.includes(user.brand)) return <Empty title="无权查看营销记录" />;
  const rows = state.participations.filter((row) => { const activity = state.activities.find((item) => item.id === row.activityId); return activity?.brand === user.brand && row.identities.some((ref) => ref.userId === userId); });
  return <Panel title="营销活动（只读引用）" note="不写入购买意向、销售流程或旧客户旅程。">{rows.length ? <Table rowKey="id" dataSource={rows} scroll={{ x: 700 }} columns={[{ title: "活动", render: (_: unknown, row: typeof rows[number]) => <a href={`#marketing/activity/${row.activityId}`}>{state.activities.find((activity) => activity.id === row.activityId)?.name}</a> }, { title: "参与 / 完成", render: (_: unknown, row: typeof rows[number]) => participationIssue(row, members) || (row.completedAt ? "已完成" : row.checkedInAt ? "已签到" : "已报名") }, { title: "预约 / 中奖 / 已履约", render: (_: unknown, row: typeof rows[number]) => `${state.bookings.filter((item) => item.participationId === row.id).length} / ${state.awards.filter((item) => item.participationId === row.id).length} / ${state.awards.filter((item) => item.participationId === row.id && item.fulfilledAt).length}` }, { title: "预览", render: (_: unknown, row: typeof rows[number]) => <a href={`#marketing/preview/${row.activityId}/${userId}`}>查看用户记录</a> }]} /> : <Empty title="此品牌用户暂无营销参与记录" />}</Panel>;
}
