import { useEffect, useMemo, useState } from "react";
import { Banner, Button, Empty, Modal, Table } from "@douyinfe/semi-ui";
import qrcode from "qrcode-generator";
import { DataList, PageHeader } from "@/components/CrmUi";
import { useCrm } from "@/stores/crm-store";
import { brandLabels, useMemberOperations } from "@/stores/member-operations-store";
import { useMarketing } from "@/stores/marketing-store";
import type { MarketingActivity, MarketingAward, MarketingBooking } from "@/types/marketing";
import { navigate } from "@/utils/format";
import { parseCreatedAt } from "@/features/dashboard/dashboard-model";
import { bookingLabels, bookingStatus, canViewMarketing, chances, claimLabels, drawBlock, marketingPermissions, needsReservation, participationFor, participationIssue, phase, resolveCredential, slotFor, slotOccupancy } from "./marketing-model";
import { MarketingDetail, MarketingList } from "./MarketingAdmin";
import { VirtualAwardContent } from "./MarketingData";
import { ActivityPhases, DemoNote, displayDate, Panel, SelectField, TextField, options, useAction } from "./MarketingUi";

const uid = () => crypto.randomUUID();
const decodeCode = (value: string) => { try { return decodeURIComponent(value); } catch { return value; } };

export function MarketingPage({ path }: { path: string[] }) {
  const pathKey = path.join("/");
  useEffect(() => { void window.scrollTo(0, 0); }, [pathKey]);
  const { currentUser } = useCrm(), access = marketingPermissions(currentUser);
  const { state, issue, reset } = useMarketing();
  if (!canViewMarketing(access) || !access.brands.length) return <div className="page"><Banner type="warning" title="当前角色无权访问营销活动" description={!access.brands.length ? "当前账号没有可管理的品牌。" : "当前账号没有活动查看权限。"} closeIcon={null} /></div>;
  if (issue) return <div className="page"><Banner type="danger" title={issue} closeIcon={null} /><Button disabled={!access.manage} onClick={() => Modal.confirm({ title: "重置营销数据？", content: "只替换营销命名空间，销售、会员和原始V1备份不变；请先手动备份无法读取的内容。", onOk: reset })}>确认后重置营销数据</Button></div>;
  if (path[0] === "activity" || path[0] === "preview") {
    const activity = state.activities.find((row) => row.id === path[1] && access.brands.includes(row.brand));
    if (!activity) return <div className="page"><Empty title="活动不存在或无权访问" /></div>;
    if (path[0] === "preview" && !access.preview) return <div className="page"><Banner type="warning" title="当前角色无权操作用户流程预览" closeIcon={null} /></div>;
    return path[0] === "preview" ? <MarketingPreview key={`${activity.id}:${path[2] || ""}`} activity={activity} initialUserId={path[2]} /> : <MarketingDetail key={activity.id} activity={activity} requestedTab={path[2]} />;
  }
  return <div className="page marketing-page"><MarketingList migratedEntry={path[0]} /></div>;
}
export function MarketingRedemptionSurface({ code = "" }: { code?: string }) {
  const { currentUser } = useCrm(), { issue } = useMarketing();
  const access = marketingPermissions(currentUser);
  if (!access.redeem || !access.brands.length) return <div className="page"><Banner type="warning" title="当前角色无权访问核销端" closeIcon={null} /></div>;
  if (issue) return <div className="page"><Banner type="danger" title={issue} closeIcon={null} /></div>;
  return <main className="marketing-redemption-surface"><header><strong>KIVISENSE · 独立核销端</strong><span>{currentUser.name} · 演示权限</span>{canViewMarketing(access) && <Button size="small" onClick={() => navigate("marketing")}>返回CRM管理后台</Button>}</header><div className="page-scroll"><RedemptionWorkbench key={code || "input"} initialCode={decodeCode(code)} /></div></main>;
}

function Credential({ code, label }: { code: string; label: string }) { const data = useMemo(() => { const qr = qrcode(0, "M"); qr.addData(code); qr.make(); return qr.createDataURL(4, 16); }, [code]); return <div className="marketing-credential"><img src={data} alt={`${label}二维码`} /><div><strong>{label}</strong><code>{code}</code><small>仅含随机演示标识，不含手机号。独立核销端输入此码，或使用“模拟扫码”读取。</small><Button size="small" onClick={() => navigate(`redemption/${encodeURIComponent(code)}`)}>模拟扫码 / 输入核验</Button></div></div>; }

function BookingTable({ rows }: { rows: MarketingBooking[] }) {
  const { state } = useMarketing(), { run, feedback } = useAction(); const [change, setChange] = useState<MarketingBooking | null>(null), [target, setTarget] = useState("");
  const activity = state.activities.find((row) => row.id === change?.activityId), slots = change?.kind === "ACTIVITY" ? activity?.slots : activity?.pool.find((item) => item.id === change?.poolItemId)?.slots;
  return <>{feedback}{rows.length ? <Table rowKey="id" dataSource={rows} pagination={{ pageSize: 10 }} scroll={{ x: 920 }} columns={[{ title: "预约类型 / 活动", width: 250, render: (_: unknown, row: MarketingBooking) => <span>{row.kind === "ACTIVITY" ? "参加活动" : "中奖履约"} · <a href={`#marketing/activity/${row.activityId}`}>{state.activities.find((activity) => activity.id === row.activityId)?.name}</a></span> }, { title: "参与主体", dataIndex: "participationId", width: 210 }, { title: "场次", width: 200, render: (_: unknown, row: MarketingBooking) => `${slotFor(state, row)?.label || "场次待核对"} · ${displayDate(slotFor(state, row)?.startAt)}` }, { title: "当前状态", width: 100, render: (_: unknown, row: MarketingBooking) => bookingLabels[bookingStatus(row, slotFor(state, row), Date.now())] }, { title: "操作", width: 160, fixed: "right", render: (_: unknown, row: MarketingBooking) => <div className="button-row"><Button size="small" disabled={row.status !== "BOOKED"} onClick={() => { setChange(row); setTarget(row.slotId); }}>改约</Button><Button size="small" disabled={row.status !== "BOOKED"} onClick={() => run({ type: "CANCEL_BOOKING", bookingId: row.id })}>取消预约</Button></div> }]} /> : <Empty title="暂无当前范围预约" description="活动与奖品预约来自同一数据源，业务类型独立。" />}{change && <Modal visible title="改约（失败保留原预约）" onCancel={() => setChange(null)} onOk={() => { if (run({ type: "RESCHEDULE", bookingId: change.id, slotId: target }).ok) setChange(null); }}>{feedback}<SelectField label="目标场次" value={target} list={(slots || []).map((slot) => ({ value: slot.id, label: `${slot.label} · ${displayDate(slot.startAt)}` }))} onChange={setTarget} /></Modal>}</>;
}

function MarketingPreview({ activity, initialUserId }: { activity: MarketingActivity; initialUserId?: string }) {
  const { state } = useMarketing(), { currentUser } = useCrm(), { state: members } = useMemberOperations(), { run, feedback } = useAction(); const users = members.brandUsers.filter((row) => row.brand === activity.brand && row.is_deleted === 0 && marketingPermissions(currentUser).brands.includes(row.brand));
  const [userId, setUserId] = useState(initialUserId || users[0]?.id || ""), [slotId, setSlotId] = useState(activity.slots[0]?.id || ""), [prizeSlots, setPrizeSlots] = useState<Record<string, string>>({}), [drawing, setDrawing] = useState(false);
  const identity = participationFor(state, activity, members, userId), row = identity.participation;
  const ctx = { actor: currentUser, members, now: Date.now() }; const reason = identity.error || drawBlock(state, activity, row, ctx), balance = row ? chances(state, row) : { earned: 0, used: 0, remaining: 0 };
  const draws = state.draws.filter((draw) => draw.participationId === row?.id), last = draws.at(-1), awards = state.awards.filter((award) => award.participationId === row?.id);
  const bookings = state.bookings.filter((booking) => booking.participationId === row?.id);
  return <div className="page marketing-preview"><Button theme="borderless" onClick={() => navigate(`marketing/activity/${activity.id}`)}>返回活动后台</Button><PageHeader title="用户流程预览" description={`${activity.name} · ${brandLabels[activity.brand]} · 非真实小程序`} /><DemoNote />{users.length > 0 && <SelectField label="预览现有品牌用户" value={userId} onChange={setUserId} list={users.map((user) => ({ value: user.id, label: user.id }))} />}{feedback}{!users.length ? <Empty title="当前品牌暂无可用参与用户。" description="活动配置与发布不依赖会员数据；不自动创建或猜测身份。" /> : identity.error ? <Banner type="warning" title={identity.error} closeIcon={null} /> : <>
    <Panel title="1 · 参加活动" note="预约只占名额，不代表完成，也不发抽奖次数。"><ActivityPhases activity={activity} /><p>{activity.description}</p>{activity.bookingEnabled && <SelectField label="参加活动场次" value={slotId} onChange={setSlotId} list={activity.slots.map((slot) => ({ value: slot.id, label: `${slot.label} · ${displayDate(slot.startAt)} · 剩余 ${Math.max(0, slot.capacity - slotOccupancy(state, activity.id, "ACTIVITY", slot.id))}` }))} />}<div className="button-row"><Button theme="solid" disabled={activity.status !== "PUBLISHED" || !userId} onClick={() => run({ type: "REGISTER", activityId: activity.id, userId, slotId: activity.bookingEnabled ? slotId : undefined })}>{activity.bookingEnabled ? "预约参加" : "直接报名参加"}</Button></div>{row && <><p>参与状态：{row.completedAt ? "已完成" : row.checkedInAt ? "已签到 / 参与中" : "已报名 / 待到场"}</p><Credential code={row.credential} label="活动凭证（签到 / 完成）" /></>}</Panel>
    <Panel title="我的预约"><BookingTable rows={bookings} /></Panel>
    {activity.lotteryEnabled && <Panel title="2 · 完成后即时抽奖" note="累计获得、已用与剩余不是配置上限。库存或个人限额不可用的奖品概率转入未中奖。"><DataList rows={[["累计获得", String(balance.earned)], ["已使用", String(balance.used)], ["剩余", String(balance.remaining)], ["活动抽奖上限", activity.drawLimit], ["不可使用原因", reason || "可抽奖"]]} /><div className="button-row"><Button theme="solid" loading={drawing} disabled={Boolean(reason) || drawing} onClick={async () => { setDrawing(true); await Promise.resolve(); run({ type: "DRAW", activityId: activity.id, userId, operationId: uid() }); setDrawing(false); }}>即时抽奖</Button>{last && <Button onClick={() => run({ type: "DRAW", activityId: activity.id, userId, operationId: last.operationId })}>重试上次请求（返回原结果）</Button>}</div>{last && <p className="marketing-draw-result" role="status">最近已保存结果：{last.poolItemId ? state.awards.find((award) => award.drawId === last.id)?.prizeName : "未中奖"} · 结果ID {last.id}</p>}</Panel>}
    <Panel title="3 · 我的奖品 / 履约" note="中奖已经占用配额。预约不重报名、不再扣抽奖机会；过期不自动返池。">{awards.length ? awards.map((award) => { const item = activity.pool.find((pool) => pool.id === award.poolItemId); const active = bookings.find((booking) => booking.awardId === award.id && ["BOOKED", "FULFILLED"].includes(booking.status)); return <section className="marketing-my-award" key={award.id}><h3>{award.prizeName}</h3><p>{claimLabels[award.method]} · {(award.fulfilledAt || award.issuedAt) ? "已领取 / 已发放" : Date.now() >= parseCreatedAt(award.claimEnd) ? "已过期，不能领取" : "待履约"}</p><p>承诺快照：{award.instructions} · 截止 {displayDate(award.claimEnd)} · 规则 v{award.ruleVersion}</p>{needsReservation(award) && !award.fulfilledAt && <><SelectField label={`奖品预约时段 ${award.id}`} value={prizeSlots[award.id] || item?.slots[0]?.id || ""} onChange={(value) => setPrizeSlots((old) => ({ ...old, [award.id]: value }))} list={(item?.slots || []).map((slot) => ({ value: slot.id, label: `${slot.label} · ${displayDate(slot.startAt)} · 剩余 ${Math.max(0, slot.capacity - slotOccupancy(state, activity.id, "PRIZE", slot.id, item?.id))}` }))} /><Button disabled={Boolean(active) || Date.now() >= parseCreatedAt(award.claimEnd)} onClick={() => run({ type: "BOOK_PRIZE", awardId: award.id, slotId: prizeSlots[award.id] || item?.slots[0]?.id || "" })}>预约奖品领取 / 体验</Button></>}{award.prizeType === "PHYSICAL" ? <Credential code={award.credential} label="奖品凭证（具体获奖权益）" /> : award.prizeType === "VIRTUAL" ? <VirtualAwardContent award={award} /> : <Banner type="warning" title="待补充奖品类型" closeIcon={null} />}</section>; }) : <Empty title="暂无获奖权益" description="未中奖也是已保存的有效抽奖结果。" />}</Panel>
  </>}</div>;
}


function WalkInPanel({ onRegistered }: { onRegistered: (credential: string) => void }) {
  const { state } = useMarketing(), { currentUser } = useCrm(), { state: members } = useMemberOperations(), { run, feedback } = useAction();
  const access = marketingPermissions(currentUser), activities = state.activities.filter((activity) => access.brands.includes(activity.brand) && activity.allowWalkIn && activity.status === "PUBLISHED");
  const [activityId, setActivityId] = useState(activities[0]?.id || ""), [userId, setUserId] = useState(""), [slotId, setSlotId] = useState("");
  const activity = activities.find((activity) => activity.id === activityId), users = members.brandUsers.filter((user) => user.brand === activity?.brand && user.is_deleted === 0 && access.brands.includes(user.brand));
  const selectedUser = users.some((user) => user.id === userId) ? userId : users[0]?.id || "", selectedSlot = activity?.slots.some((slot) => slot.id === slotId) ? slotId : activity?.slots[0]?.id || "";
  return <Panel title="工作人员现场报名" note="仅限已发布且允许现场报名的授权品牌活动；同主体已有预约将返回原记录，不产生第二身份，不按电话 / UnionID猜测会员。">
    {feedback}{activities.length ? <><SelectField label="现场报名活动" value={activityId} list={activities.map((activity) => ({ value: activity.id, label: `${activity.name} · ${brandLabels[activity.brand]}` }))} onChange={(value) => { setActivityId(value); setUserId(""); setSlotId(""); }} />
      {users.length ? <><SelectField label="现场报名品牌用户" value={selectedUser} list={users.map((user) => ({ value: user.id, label: user.id }))} onChange={setUserId} />{activity?.bookingEnabled && <SelectField label="现场报名场次" value={selectedSlot} list={activity.slots.filter((slot) => !slot.disabled && !slot.deleted).map((slot) => ({ value: slot.id, label: `${slot.label} · ${displayDate(slot.startAt)} · 剩余${Math.max(0, slot.capacity - slotOccupancy(state, activity.id, "ACTIVITY", slot.id))}` }))} onChange={setSlotId} />}
      <Button theme="solid" disabled={!access.redeem || !activity} onClick={() => { if (!activity) return; const result = run({ type: "REGISTER", activityId: activity.id, userId: selectedUser, slotId: activity.bookingEnabled ? selectedSlot : undefined, walkIn: true }); const participant = result.state.participations.find((participant) => participant.id === result.resultId); if (result.ok && participant) onRegistered(participant.credential); }}>确认现场报名</Button></> : <Empty title="当前品牌暂无可用参与用户。" description="请选择其他授权品牌活动，不能临时创建或合并身份。" />}
    </> : <Empty title="暂无允许现场报名的已发布活动" />}
  </Panel>;
}
function RedemptionWorkbench({ initialCode = "" }: { initialCode?: string }) {
  const { state } = useMarketing(), { currentUser } = useCrm(), { state: members } = useMemberOperations(), { run, feedback } = useAction(); const [code, setCode] = useState(initialCode), [recognized, setRecognized] = useState(""), [action, setAction] = useState("CHECKIN"), [location, setLocation] = useState(""), [slotId, setSlotId] = useState("");
  const ctx = { actor: currentUser, members, now: Date.now() }, token = recognized ? resolveCredential(state, recognized, ctx) : null;
  const booking = state.bookings.find((row) => token?.award ? row.awardId === token.award.id && row.status === "BOOKED" : row.participationId === token?.participation?.id && row.kind === "ACTIVITY" && ["BOOKED", "CHECKED_IN"].includes(row.status));
  const slot = booking && slotFor(state, booking);
  const recognize = () => { setRecognized(code.trim()); const result = resolveCredential(state, code.trim(), ctx); const matched = state.bookings.find((row) => result.award ? row.awardId === result.award.id && row.status === "BOOKED" : row.participationId === result.participation?.id && row.kind === "ACTIVITY" && ["BOOKED", "CHECKED_IN"].includes(row.status)); const matchedSlot = matched && slotFor(state, matched); setAction(result.award ? "CLAIM" : result.participation?.checkedInAt ? "COMPLETE" : "CHECKIN"); setLocation(matchedSlot?.location ?? result.award?.location ?? result.activity?.location ?? ""); setSlotId(matchedSlot?.id ?? ""); };
  return <div className="marketing-redemption"><PageHeader title="核销端" description="活动签到、完成确认与奖品核销分别执行；先识别再明确确认。" /><DemoNote /><div className="marketing-toolbar"><TextField label="演示凭证码" value={code} onChange={(value) => { setCode(value); setRecognized(""); }} /><Button theme="solid" onClick={recognize}>识别凭证 / 模拟扫码</Button></div>{feedback}{token?.error && <Banner type="warning" title={token.error} closeIcon={null} />}{token?.activity && token.participation && <Panel title="核验后确认" note="未到窗口、已取消、过期、类型 / 品牌 / 地点不符都会拒绝，不模拟成功。"><DataList rows={[["凭证类型", token.award ? "具体获奖权益" : "活动参与"], ["活动", token.activity.name], ["品牌", brandLabels[token.activity.brand]], ["用户引用", token.participation.identities.map((row) => row.userId).join(" · ")], ["奖品 / 当前状态", token.award ? `${token.award.prizeName} · ${token.award.fulfilledAt ? "已履约" : phase(Date.now(), token.award.claimStart, token.award.claimEnd)}` : token.participation.completedAt ? "已完成" : token.participation.checkedInAt ? "已签到 / 参与中" : "待到场"], ["预约场次", slot ? `${slot.label} · ${displayDate(slot.startAt)} · ${bookingLabels[bookingStatus(booking!, slot, Date.now())]}` : "没有有效预约"], ["允许窗口", slot ? `${displayDate(slot.checkinStart)} 至 ${displayDate(slot.checkinEnd)}` : "按活动 / 奖品有效期"]]} /><div className="marketing-form-grid"><SelectField label="本次核验动作" value={action} onChange={setAction} list={[{ value: "CHECKIN", label: "活动签到（不默认完成）" }, { value: "COMPLETE", label: "工作人员确认完成（不默认领奖）" }, { value: "CLAIM", label: "奖品领取 / 体验核销" }]} /><TextField label="当前核验地点" value={location} onChange={setLocation} /><TextField label="本次场次标识" value={slotId} onChange={setSlotId} /></div><Button theme="solid" onClick={() => Modal.confirm({ title: "确认执行核验？", content: `${options({ CHECKIN: "活动签到", COMPLETE: "完成确认", CLAIM: "奖品核销" }).find((row) => row.value === action)?.label} · ${token.activity!.name} · ${location}，会按当前真实状态验证。`, onOk: () => { run({ type: "VERIFY", credential: recognized, action: action as "CHECKIN" | "COMPLETE" | "CLAIM", location, slotId }); } })}>确认执行所选动作</Button></Panel>}{!recognized && <Empty title="请输入或从用户预览带入凭证码" description="二维码编码同一个可核验演示标识；没有摄像头时使用输入 / 模拟扫码。" />}<WalkInPanel onRegistered={(credential) => { setCode(credential); setRecognized(""); }} /></div>;
}

export function MemberMarketingRecords({ userId }: { userId: string }) {
  const { state } = useMarketing(), { currentUser } = useCrm(), { state: members } = useMemberOperations(); const user = members.brandUsers.find((row) => row.id === userId), brands = marketingPermissions(currentUser).brands;
  if (!user || !brands.includes(user.brand) || !canViewMarketing(marketingPermissions(currentUser))) return <Empty title="无权查看营销记录" />;
  const rows = state.participations.filter((row) => { const activity = state.activities.find((item) => item.id === row.activityId); return activity?.brand === user.brand && row.identities.some((ref) => ref.userId === userId); });
  return <Panel title="营销活动（只读引用）" note="不写入购买意向、销售流程或旧客户旅程。">{rows.length ? <Table rowKey="id" dataSource={rows} scroll={{ x: 700 }} columns={[{ title: "活动", render: (_: unknown, row: typeof rows[number]) => <a href={`#marketing/activity/${row.activityId}`}>{state.activities.find((activity) => activity.id === row.activityId)?.name}</a> }, { title: "参与 / 完成", render: (_: unknown, row: typeof rows[number]) => participationIssue(row, members) || (row.completedAt ? "已完成" : row.checkedInAt ? "已签到" : "已报名") }, { title: "预约 / 中奖 / 已履约", render: (_: unknown, row: typeof rows[number]) => `${state.bookings.filter((item) => item.participationId === row.id).length} / ${state.awards.filter((item) => item.participationId === row.id).length} / ${state.awards.filter((item) => item.participationId === row.id && item.fulfilledAt).length}` }, { title: "预览", render: (_: unknown, row: typeof rows[number]) => <a href={`#marketing/preview/${row.activityId}/${userId}`}>查看用户记录</a> }]} /> : <Empty title="此品牌用户暂无营销参与记录" />}</Panel>;
}
