import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Banner, Button, Empty, Input, Select, SideSheet, TabPane, Table, Tabs } from "@douyinfe/semi-ui";
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { PageHeader } from "@/components/CrmUi";
import { useCrm } from "@/stores/crm-store";
import { useMemberOperations } from "@/stores/member-operations-store";
import type { MemberBrandScope } from "@/types/member-operations";
import { navigate } from "@/utils/format";
import { brandScopeLabels } from "@/utils/brand-display";
import { association, buildDashboard, hqCategory, hqLabels, leadLabels, openStages, ratio, recordLabel, resolveRange, shanghaiDate, stageLabels, winRate, type Cohort, type DashboardRecord, type DashboardSnapshot, type PeriodPreset, type RecordKind, type RowGroup } from "./dashboard-model";

type DetailSection = { label: string; kind: RecordKind; rows: DashboardRecord[] };
type Detail = { title: string; basis: string; sections: DetailSection[]; scope: string; time: string };
const sources = { sales: "Kivisense 销售演示", members: "Kivisense 会员演示" };
const basis = { period: "本期创建，截至当前", current: "截至当前，不随日期筛选变化" };
const timeLabel = (now: number) => `${shanghaiDate(now)} ${new Date(now + 8 * 3_600_000).toISOString().slice(11, 19)} UTC+08`;

export function DashboardPage({ view: routeView }: { view?: string }) {
  const { state, currentUser, isHq } = useCrm();
  const { state: memberState, recoveryIssue: memberRecoveryIssue } = useMemberOperations();
  const [preset, setPreset] = useState<PeriodPreset>("30");
  const [custom, setCustom] = useState({ from: "", to: "" });
  const [distributorId, setDistributorId] = useState("all");
  const [brand, setBrand] = useState<MemberBrandScope>("ALL");
  const [now, setNow] = useState(Date.now);
  const [detail, setDetail] = useState<Detail | null>(null);
  const view = routeView === "sales" ? "sales" : routeView === "members" ? "members" : "business";
  const period = useMemo(() => resolveRange(preset, now, custom.from, custom.to), [preset, now, custom]);
  const snapshot = useMemo(() => period.range ? buildDashboard(state, memberState, { range: period.range, actor: currentUser, distributorId: isHq ? distributorId : "all", brand }) : null, [state, memberState, period, currentUser, isHq, distributorId, brand]);
  useEffect(() => { setDetail(null); }, [currentUser.id, state, memberState, memberRecoveryIssue, preset, custom, distributorId, brand, now]);
  const title = view === "sales" ? "销售概览" : view === "members" ? "会员运营概览" : "业务总览";
  const description = view === "sales" ? "新增业务、当前销售进展与待处理工作。" : view === "members" ? "集团客户、品牌档案与购买意向，不等同于成交或营销效果分析。" : "分别查看销售业务和会员运营，不混合客户身份与业务口径。";
  const salesScope = isHq ? state.distributors.find((row) => row.id === distributorId)?.name || "全部授权分销商" : state.distributors.find((row) => row.id === currentUser.distributorId)?.name || "当前分销商";
  const memberScope = brand === "ALL" ? "全部授权品牌" : brandScopeLabels[brand];
  const open = (title: string, kind: RecordKind, rows: DashboardRecord[], temporal: "period" | "current" = "period", note = "", sections?: DetailSection[]) => {
    if (!period.range) return;
    const member = ["user", "intent", "customer"].includes(kind);
    setDetail({ title, sections: sections ?? [{ label: "匹配记录", kind, rows }], basis: `${temporal === "period" ? `${basis.period} · 创建日期 ${period.range.label}` : basis.current}${note ? ` · ${note}` : ""}`, scope: `${member ? sources.members : sources.sales} · ${member ? memberScope : salesScope} · 当前角色授权范围`, time: timeLabel(now) });
  };
  const count = (label: string, kind: RecordKind, rows: DashboardRecord[], temporal: "period" | "current" = "period", note = "", value?: string | number, sections?: DetailSection[]) => <button className="dashboard-number" aria-label={`${label}：查看明细`} onClick={() => open(label, kind, rows, temporal, note, sections)}>{value ?? rows.length}</button>;
  const metric = (label: string, kind: RecordKind, rows: DashboardRecord[], temporal: "period" | "current", note: string, value?: string | number, sections?: DetailSection[]) => <div className="overview-metric"><span>{label}</span>{count(label, kind, rows, temporal, note, value, sections)}<small>{note}</small></div>;
  const periodMetric = <T extends DashboardRecord,>(label: string, kind: RecordKind, c: Cohort<T>, note = "按创建时间，全部当前状态") => metric(label, kind, c.rows, "period", `${note}${c.unknown.length ? `；${c.unknown.length} 条日期待补，未纳入` : ""}`, c.available ? c.rows.length : "暂不可统计");
  const coverage = <T extends DashboardRecord,>(label: string, kind: RecordKind, c: Cohort<T>) => <div className="dashboard-coverage"><span>{label}：{c.available ? "按已知创建日期统计" : "暂不可统计：缺少创建时间"}</span>{c.unknown.length > 0 && count(`${label}日期待补（未纳入）`, kind, c.unknown, "current", "缺少或无效创建时间", `${c.unknown.length} 条日期待补（未纳入）`)}{c.future.length > 0 && count(`${label}未来日期（未纳入）`, kind, c.future, "current", "创建时间晚于查看时刻", `${c.future.length} 条未来记录（未纳入）`)}</div>;
  const distribution = <T extends DashboardRecord,>(title: string, groups: RowGroup<T>[], kind: RecordKind, temporal: "period" | "current", note: string, available = true) => {
    if (!available) return <Panel title={title} note={note}><Empty title="暂不可统计：缺少可用创建时间" description="日期待补记录未纳入；不显示为零分布。" /></Panel>;
    const total = groups.reduce((sum, group) => sum + group.rows.length, 0);
    return <Panel title={title} note={note}><div className="dashboard-distribution">{groups.map((group) => <div key={group.key}><span>{group.label}</span><button className="dashboard-bar-track" aria-label={`${title} / ${group.label}：查看图表明细`} onClick={() => open(`${title} / ${group.label}`, kind, group.rows, temporal, group.label)}><span style={{ width: `${total ? group.rows.length / total * 100 : 0}%` }} /></button>{count(`${title} / ${group.label}`, kind, group.rows, temporal, group.label)} <small>{count(`${title} / ${group.label}占比`, kind, group.rows, temporal, "分母为本图全部分类记录", ratio(group.rows.length, total), [{ label: "分子：" + group.label, kind, rows: group.rows }, { label: "分母：本图全部分类记录", kind, rows: groups.flatMap((item) => item.rows) }])}</small></div>)}</div>{total === 0 && <p className="dashboard-empty-note">当前口径暂无可计算记录；可点击分类查看空明细。</p>}</Panel>;
  };
  const attention = (label: string, kind: RecordKind, rows: DashboardRecord[], owner: string, note: string) => <section className="dashboard-attention"><header><div><h3>{label}</h3><small>{owner} · {note}</small></div>{count(label, kind, rows, "current", note)}<Button size="small" theme="borderless" onClick={() => open(label, kind, rows, "current", note)}>查看全部</Button></header>{rows.length ? <ul>{rows.slice(0, 3).map((row) => <li key={row.id}><span>{recordLabel(row)}</span>{"error" in row && row.error?.trim() && <small>{row.error}</small>}</li>)}</ul> : <p className="dashboard-empty-note">暂无匹配记录</p>}</section>;
  function salesSummary(s: DashboardSnapshot) { return <Panel title="销售摘要" note={`${sources.sales} · ${salesScope}`} action={<Button size="small" theme="borderless" onClick={() => navigate("dashboard/sales")}>查看销售概览</Button>}><div className="overview-metrics four">{periodMetric("本期新增 Lead", "lead", s.leadCohort)}{periodMetric("本期新增 Deal", "deal", s.dealCohort)}{metric("当前进行中 Deal", "deal", s.openDeals, "current", "全部创建日期 · 当前开放阶段")}{metric("当前逾期销售任务", "task", s.overdueTasks, "current", "OPEN 且到期时间早于查看时刻")}</div></Panel>; }
  function memberSummary(s: DashboardSnapshot) { return <Panel title="会员摘要" note={`${sources.members} · ${memberScope}`} action={<Button size="small" theme="borderless" onClick={() => navigate("dashboard/members")}>查看会员运营概览</Button>}>{memberRecoveryIssue ? <Banner type="warning" title={memberRecoveryIssue} description="会员指标暂不可统计；原始数据已保留，请由管理员在 Settings 明确确认恢复。销售统计不受影响。" closeIcon={null} /> : <div className="overview-metrics four">{periodMetric("本期新增品牌档案", "user", s.userCohort, "本期创建、当前未删除")}{periodMetric("本期新增购买意向", "intent", s.intentCohort)}{metric("当前未关联会员的意向", "intent", s.unlinkedIntents, "current", "允许未关联，待核查；不是故障")}{metric("当前同步异常", "intent", s.syncAnomalies, "current", "未同步且错误信息非空")}</div>}</Panel>; }
  function trends(s: DashboardSnapshot, member: boolean) {
    const series = member ? [{ key: "users" as const, label: "品牌档案", kind: "user" as const, color: "#087a4b" }, { key: "intents" as const, label: "购买意向", kind: "intent" as const, color: "#315f8c" }] : [{ key: "leads" as const, label: "Lead", kind: "lead" as const, color: "#087a4b" }, { key: "deals" as const, label: "Deal", kind: "deal" as const, color: "#315f8c" }];
    const availability = { users: s.userCohort.available, intents: s.intentCohort.available, leads: s.leadCohort.available, deals: s.dealCohort.available };
    const data = s.trend.map((bucket, index) => ({ label: bucket.label, index, ...Object.fromEntries(series.map((item) => [item.key, availability[item.key] ? bucket[item.key].length : null])) }));
    const available = series.some((item) => availability[item.key]);
    const hasRows = series.some((item) => s.trend.some((bucket) => bucket[item.key].length > 0));
    const point = (index: number, item: typeof series[number]) => { const bucket = s.trend[index]; if (bucket) open(`新增趋势 / ${item.label} / ${bucket.label}`, item.kind, bucket[item.key], "period", `分桶 ${shanghaiDate(bucket.start)} — ${shanghaiDate(bucket.end - 1)}（左闭右开）；同日重合点同时列出两类，互非转化`, series.map((entry) => ({ label: `${entry.label}${availability[entry.key] ? "" : "（暂不可统计）"}`, kind: entry.kind, rows: bucket[entry.key] }))); };
    const trendDot = (props: { cx?: number; cy?: number; payload?: { index: number } }, item: typeof series[number]) => {
      const index = props.payload?.index ?? 0, bucket = s.trend[index];
      const overlap = series.every((entry) => availability[entry.key]) && bucket[series[0].key].length === bucket[series[1].key].length;
      if (!availability[item.key] || (overlap && item.key === series[0].key)) return <g key={index} />;
      const label = overlap ? series.map((entry) => entry.label).join(" 与 ") : item.label;
      return <circle key={index} cx={props.cx} cy={props.cy} r={4} fill={item.color} tabIndex={0} role="button" aria-label={`${label} ${bucket.label}：查看趋势明细`} onClick={() => point(index, item)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); point(index, item); } }} />;
    };
    return <Panel title={member ? "新增品牌档案与购买意向趋势" : "新增 Lead 与 Deal 趋势"} note="单位：条 · 同一创建期，分别计数，不代表因果转化；点击数据点查看记录。">
      {available && hasRows ? <ResponsiveContainer width="100%" height={210} debounce={80}><LineChart data={data} margin={{ left: 0, right: 14, top: 12, bottom: 0 }}><CartesianGrid stroke="#eceee9" vertical={false} /><XAxis dataKey="label" tickLine={false} axisLine={false} minTickGap={28} /><YAxis tickLine={false} axisLine={false} allowDecimals={false} width={34} /><Tooltip /><Legend />{series.map((item) => <Line key={item.key} dataKey={item.key} name={item.label} stroke={item.color} strokeWidth={2} isAnimationActive={false} activeDot={false} dot={(props) => trendDot(props, item)} />)}</LineChart></ResponsiveContainer> : <Empty title={available ? "所选期间暂无新增记录" : "暂不可统计：部分序列缺少创建时间"} description="缺失日期不补到今天；下方保留同口径分桶明细。" />}
      <details className="dashboard-trend-details"><summary>查看逐桶数值与记录</summary><div className="dashboard-table-scroll"><table><thead><tr><th>创建日期（Asia/Shanghai）</th>{series.map((item) => <th key={item.key}>{item.label}（条）</th>)}</tr></thead><tbody>{s.trend.map((bucket) => <tr key={bucket.start}><td>{shanghaiDate(bucket.start)} — {shanghaiDate(bucket.end - 1)}</td>{series.map((item) => <td key={item.key}>{count(`${item.label}趋势 / ${bucket.label}`, item.kind, bucket[item.key], "period", `分桶 ${shanghaiDate(bucket.start)} — ${shanghaiDate(bucket.end - 1)}`, availability[item.key] ? undefined : "暂不可统计")}</td>)}</tr>)}</tbody></table></div></details>
    </Panel>;
  }
  function analysisTable(title: string, rows: DashboardSnapshot["products"], product: boolean, availability: { leads: boolean; deals: boolean }) { return <Panel title={title} note="本期创建，截至当前；按记录当前归属分组，并非历史归属归因。"><div className="dashboard-table-scroll"><table><thead><tr><th>{product ? "销售产品" : "分销商"}</th>{!product && <th>本期新增 Lead</th>}<th>本期新增 Deal</th>{product && <th>其中当前进行中</th>}<th>其中当前赢单</th><th>其中当前输单</th></tr></thead><tbody>{rows.map((row) => <tr key={row.key}><td>{row.label}</td>{!product && <td>{count(`${row.label} / 新增 Lead`, "lead", row.leads, "period", "按已知创建日期统计，缺失日期排除", availability.leads ? undefined : "暂不可统计")}</td>}<td>{count(`${row.label} / 新增 Deal`, "deal", row.deals, "period", "按已知创建日期统计，缺失日期排除", availability.deals ? undefined : "暂不可统计")}</td>{product && <td>{count(`${row.label} / 其中当前进行中`, "deal", row.deals.filter((deal) => openStages.includes(deal.stage)), "period", "按已知创建日期统计，缺失日期排除", availability.deals ? undefined : "暂不可统计")}</td>}<td>{count(`${row.label} / 其中当前赢单`, "deal", row.won, "period", "按已知创建日期统计，缺失日期排除", availability.deals ? undefined : "暂不可统计")}</td><td>{count(`${row.label} / 其中当前输单`, "deal", row.lost, "period", "按已知创建日期统计，缺失日期排除", availability.deals ? undefined : "暂不可统计")}</td></tr>)}</tbody></table></div></Panel>; }
  function salesView(s: DashboardSnapshot) {
    const won = s.outcomes.find((group) => group.key === "WON")!.rows, lost = s.outcomes.find((group) => group.key === "LOST")!.rows;
    return <>
      <Panel title="本期新增" note={basis.period}><div className="overview-metrics three">{periodMetric("新增 Lead", "lead", s.leadCohort)}{periodMetric("新增 Deal", "deal", s.dealCohort)}{metric("新增 Lead 转 Deal 比例", "lead", s.conversion.confirmed, "period", "本期创建的 Lead，截至当前已确认转 Deal；无分母时 —（暂无可计算记录）", s.leadCohort.available ? ratio(s.conversion.confirmed.length, s.leadCohort.rows.length) : "暂不可统计", [{ label: "分子：已确认转 Deal 的 Lead", kind: "lead", rows: s.conversion.confirmed }, { label: "分母：本期创建的全部 Lead", kind: "lead", rows: s.leadCohort.rows }])}</div></Panel>
      <Panel title="当前待处理" note={basis.current}><div className="overview-metrics two">{metric("当前进行中 Deal", "deal", s.openDeals, "current", "DISCOVERY / SOLUTION / QUOTATION / NEGOTIATION")}{metric("当前逾期销售任务", "task", s.overdueTasks, "current", "OPEN 且到期时间早于查看时刻")}</div></Panel>
      <div className="dashboard-data-notes">{coverage("Lead", "lead", s.leadCohort)}{coverage("Deal", "deal", s.dealCohort)}{count("转换数据待核验", "lead", s.conversion.conflicts, "period", "状态与关联不一致，不计入确认转化", `${s.conversion.conflicts.length} 条转换数据待核验`)}{count("当前未知 Deal 阶段", "deal", s.unknownDeals, "current", "未纳入进行中", `${s.unknownDeals.length} 条未知阶段待核验`)}</div>
      {trends(s, false)}
      <div className="dashboard-grid">{distribution("本期新增 Lead 的当前状态", s.leadStatuses, "lead", "period", basis.period, s.leadCohort.available)}{distribution("当前进行中 Deal 的阶段分布", s.currentStages, "deal", "current", basis.current)}{distribution("本期新增 Deal 的当前结果", s.outcomes, "deal", "period", basis.period, s.dealCohort.available)}<Panel title="已结案记录胜率" note="本期创建，截至当前已结案；不是本期成交胜率。"><div className="overview-metrics">{metric("已结案记录胜率", "deal", won, "period", "分子：当前 WON；分母：当前 WON + LOST", s.dealCohort.available ? winRate(s.dealCohort.rows) : "暂不可统计", [{ label: "分子：当前赢单", kind: "deal", rows: won }, { label: "分母：当前已结案", kind: "deal", rows: [...won, ...lost] }])}</div></Panel></div>
      {attention("当前逾期销售任务", "task", s.overdueTasks, sources.sales, "截至当前 · 全部创建日期")}
      <details className="dashboard-secondary"><summary>渠道与产品分析</summary>{analysisTable("分销商分析", s.distributors, false, { leads: s.leadCohort.available, deals: s.dealCohort.available })}{analysisTable("销售产品分析", s.products, true, { leads: s.leadCohort.available, deals: s.dealCohort.available })}<Panel title="产品 Add-on 分析" note="本期创建的 Deal，截至当前；按产品 + capability id 分组。同名能力不跨产品合并。Lead 兴趣为名称数组，缺少可靠产品归属，暂不分配到 Add-on。"><div className="dashboard-table-scroll"><table><thead><tr><th>产品 / Add-on</th><th>本期新增 Deal</th><th>其中当前赢单</th></tr></thead><tbody>{s.addons.map((row) => <tr key={row.key}><td>{row.label}</td><td>{count(`${row.label} / 新增 Deal`, "deal", row.deals, "period", "按已知创建日期统计，缺失日期排除", s.dealCohort.available ? undefined : "暂不可统计")}</td><td>{count(`${row.label} / 当前赢单`, "deal", row.won, "period", "本期创建，截至当前", s.dealCohort.available ? undefined : "暂不可统计")}</td></tr>)}</tbody></table></div></Panel></details>
    </>;
  }
  function membersView(s: DashboardSnapshot) {
    const invalid = s.intents.filter((row) => association(row, s.effectiveUsers) === "invalid");
    return <>
      <Panel title="当前规模" note={basis.current}><div className="overview-metrics three">{s.access.group && metric(brand === "ALL" ? "集团客户记录数" : "本品牌关联集团客户数", "customer", s.customers, "current", "按 customer.id 去重，不与档案数相加")}{metric("品牌档案数", "user", s.effectiveUsers, "current", "当前未删除；按品牌用户档案计数，非跨品牌去重人数", s.users.length > 0 && s.unknownDeletion.length === s.users.length ? "暂不可统计" : undefined)}{metric("当前购买意向数", "intent", s.intents, "current", "独立购买意向记录，非 Sales Lead / Deal")}</div></Panel>
      <Panel title="本期新增" note={basis.period}><div className="overview-metrics two">{periodMetric("新增品牌档案", "user", s.userCohort, "本期创建、当前未删除；非历史注册事件量")}{periodMetric("本期新增购买意向", "intent", s.intentCohort)}</div></Panel>
      <div className="dashboard-data-notes">{coverage("品牌档案（含待补删除状态）", "user", s.userDateCoverage)}{coverage("购买意向", "intent", s.intentCohort)}{count("删除状态待补", "user", s.unknownDeletion, "current", "删除状态未知，不计有效档案；保留原数据", `${s.unknownDeletion.length} 条删除状态待补（未纳入有效档案）`)}{count("未关联集团的品牌档案", "user", s.noCustomer, "current", "集团关联允许为空", `${s.noCustomer.length} 条未关联集团`)}{s.access.group && count("集团关联待核验", "user", s.invalidCustomer, "current", "引用不存在的可见集团，不补建对象", `${s.invalidCustomer.length} 条集团关联待核验`)}</div>
      <Panel title="品牌对比" note="品牌列仅限授权范围；当前与本期新增口径分别标明。"><div className="dashboard-table-scroll"><table><thead><tr><th>品牌</th><th>当前档案</th><th>本期新增档案</th><th>本期新增意向</th><th>当前未关联意向</th><th>当前同步异常</th></tr></thead><tbody>{s.brandComparison.map((row) => <tr key={row.brand}><td>{brandScopeLabels[row.brand]}</td><td>{count(`${brandScopeLabels[row.brand]} / 当前档案`, "user", row.current, "current", "未知删除状态排除", row.currentAvailable ? undefined : "暂不可统计")}</td><td>{count(`${brandScopeLabels[row.brand]} / 新增档案`, "user", row.newUsers.rows, "period", "当前未删除", row.newUsers.available ? undefined : "暂不可统计")}</td><td>{count(`${brandScopeLabels[row.brand]} / 新增意向`, "intent", row.newIntents.rows, "period", "", row.newIntents.available ? undefined : "暂不可统计")}</td><td>{count(`${brandScopeLabels[row.brand]} / 未关联意向`, "intent", row.unlinked, "current")}</td><td>{count(`${brandScopeLabels[row.brand]} / 同步异常`, "intent", row.anomalies, "current")}</td></tr>)}</tbody></table></div></Panel>
      {s.groupRelationships.length > 0 && distribution("集团品牌关系结构", s.groupRelationships, "customer", "current", "前三类互斥，合计为至少关联一个有效品牌用户的集团；无有效关系单列。不按电话或 UnionID 合并。")}
      {trends(s, true)}
      <div className="dashboard-grid">{distribution("本期购买意向的关联状态", s.associations, "intent", "period", `${basis.period} · 关联率不是成交转化率`, s.intentCohort.available)}{distribution("当前 HQ 同步状态", s.syncGroups, "intent", "current", "按原始同步状态与错误信息区分；未同步不是失败。")}</div>
      <Panel title="意向商品分布" note="本期创建，截至当前；品牌 + SKU，缺 SKU 回退品牌 + 型号，每条意向仅计一次。原编码为演示配置 / 字典待配置，不是软件产品。">{s.merchandise.length ? <div className="dashboard-table-scroll"><table><thead><tr><th>品牌 / 商品（原编码）</th><th>本期购买意向（条）</th></tr></thead><tbody>{s.merchandise.map((row) => <tr key={row.key}><td>{row.label}</td><td>{count(`商品 / ${row.label}`, "intent", row.rows)}</td></tr>)}</tbody></table></div> : <Empty title={s.intentCohort.available ? "本期暂无可展示商品记录" : "暂不可统计：缺少创建时间"} />}</Panel>
      <Panel title="待核查" note="均为当前存量，不受日期筛选影响；分类可重叠，不相加。"><div className="dashboard-attention-grid">{attention("当前未关联会员的意向", "intent", s.unlinkedIntents, sources.members, "允许的业务状态 · 待核查")}{attention("当前关联待核验意向", "intent", invalid, sources.members, "关联无效、跨品牌或已删除")}{attention("当前同步异常", "intent", s.syncAnomalies, sources.members, "未同步且错误信息非空")}{attention("同步状态与错误不一致", "intent", s.intents.filter((row) => hqCategory(row) === "inconsistent"), sources.members, "已同步但仍有错误 · 待核验")}</div></Panel>
    </>;
  }
  return <div className="page dashboard-page">
    <Tabs type="line" activeKey={view} onChange={(key) => navigate(key === "business" ? "dashboard" : `dashboard/${key}`)} className="dashboard-tabs"><TabPane tab="业务总览" itemKey="business" /><TabPane tab="销售概览" itemKey="sales" />{isHq && <TabPane tab="会员运营概览" itemKey="members" />}</Tabs>
    <span className="dashboard-sr-only" id="dashboard-period-label">统计周期</span><span className="dashboard-sr-only" id="dashboard-distributor-label">销售分销商范围</span><span className="dashboard-sr-only" id="dashboard-brand-label">概览品牌范围</span>
    <PageHeader title={title} description={description} actions={<div className="dashboard-filters"><Select aria-labelledby="dashboard-period-label" value={preset} onChange={(value) => setPreset(String(value) as PeriodPreset)} optionList={[{ value: "today", label: "今天" }, { value: "7", label: "最近 7 个自然日" }, { value: "30", label: "最近 30 个自然日" }, { value: "month", label: "本月" }, { value: "quarter", label: "本季度" }, { value: "custom", label: "自定义日期" }]} />{preset === "custom" && <><Input aria-label="开始日期" type="date" value={custom.from} onChange={(value) => setCustom((current) => ({ ...current, from: value }))} /><Input aria-label="结束日期" type="date" value={custom.to} onChange={(value) => setCustom((current) => ({ ...current, to: value }))} /></>}{view !== "members" && isHq && <Select aria-labelledby="dashboard-distributor-label" value={distributorId} onChange={(value) => setDistributorId(String(value))} optionList={[{ value: "all", label: "全部授权分销商" }, ...state.distributors.map((row) => ({ value: row.id, label: row.name }))]} />}{view !== "sales" && isHq && <Select aria-labelledby="dashboard-brand-label" value={brand} onChange={(value) => setBrand(String(value) as MemberBrandScope)} optionList={[{ value: "ALL", label: "全部授权品牌" }, { value: "gp", label: brandScopeLabels.gp }, { value: "un", label: brandScopeLabels.un }]} />}</div>} />
    <div className="dashboard-context"><span>{period.range ? `创建期：${period.range.label} · Asia/Shanghai` : "自定义创建期尚未有效"}</span><span>数据更新时间 / 查看时刻：{timeLabel(now)} <Button size="small" theme="borderless" onClick={() => setNow(Date.now())}>刷新统计</Button></span></div>
    {period.error && <Banner type="warning" title={period.error} closeIcon={null} />}
    {view === "members" && !isHq ? <Banner type="warning" title="当前角色无权查看会员运营概览" closeIcon={null} /> : view === "members" && memberRecoveryIssue ? <Banner type="warning" title={memberRecoveryIssue} description="会员指标暂不可统计；原始数据已保留，请由管理员在 Settings 明确确认恢复。" closeIcon={null} /> : snapshot && <>
      <p className="dashboard-source-note">{view === "sales" ? `${sources.sales} · ${salesScope}` : view === "members" ? `${sources.members} · ${memberScope}` : isHq ? `${sources.sales} 与 ${sources.members}为不同企业的模拟数据，仅并列展示，不合并客户总量或转化指标。` : `${sources.sales} · ${salesScope} · 仅限当前分销商授权数据。`}</p>
      {view === "business" ? <><div className={`dashboard-summaries ${isHq ? "" : "sales-only"}`}>{salesSummary(snapshot)}{isHq && memberSummary(snapshot)}</div><div className="dashboard-data-notes">{coverage("Lead", "lead", snapshot.leadCohort)}{coverage("Deal", "deal", snapshot.dealCohort)}{isHq && !memberRecoveryIssue && <>{coverage("品牌档案（含待补删除状态）", "user", snapshot.userDateCoverage)}{coverage("购买意向", "intent", snapshot.intentCohort)}{count("删除状态待补", "user", snapshot.unknownDeletion, "current", "不计有效品牌档案", `${snapshot.unknownDeletion.length} 条删除状态待补`)}</>}</div><Panel title="需要关注" note="当前记录，分类可能重叠；不相加成为异常总数。"><div className="dashboard-attention-grid">{attention("当前逾期销售任务", "task", snapshot.overdueTasks, sources.sales, "OPEN 且逾期")}{isHq && !memberRecoveryIssue && <>{attention("当前未关联会员的意向", "intent", snapshot.unlinkedIntents, sources.members, "允许未关联 · 待核查")}{attention("当前同步异常", "intent", snapshot.syncAnomalies, sources.members, "未同步且有错误")}</>}</div></Panel></> : view === "sales" ? salesView(snapshot) : membersView(snapshot)}
    </>}
    <SideSheet closeOnEsc title={detail?.title || "指标明细"} visible={Boolean(detail)} onCancel={() => setDetail(null)} width={Math.min(720, typeof window === "undefined" ? 720 : window.innerWidth - 24)}>{detail && <div className="dashboard-drilldown"><p>{detail.scope}</p><p>{detail.basis}</p><p>固定查看时刻：{detail.time} · 只读，不修改业务记录</p>{detail.sections.map((section, index) => <section key={index}><h3>{section.label} · {section.rows.length} 条</h3>{section.rows.length ? <Table rowKey="id" pagination={{ pageSize: 10 }} scroll={{ x: 580 }} dataSource={section.rows} columns={[{ title: "记录", width: 270, render: (_: unknown, row: DashboardRecord) => <span>{recordLabel(row)}<small className="dashboard-record-id">{row.id}</small></span> }, { title: "当前状态 / 来源", width: 170, render: (_: unknown, row: DashboardRecord) => "stage" in row ? stageLabels[row.stage] || "未知阶段" : "status" in row ? leadLabels[row.status] || row.status : "hq_sync_status" in row ? `${brandScopeLabels[row.brand]} · ${hqLabels[hqCategory(row)]}${row.error?.trim() ? ` · ${row.error}` : ""}` : "brand" in row ? `${brandScopeLabels[row.brand]} · ${row.is_deleted === 0 ? "未删除" : row.is_deleted === 1 ? "已删除" : "删除状态待补"}` : "集团客户记录" }, { title: "创建时间 / 到期时间", width: 180, render: (_: unknown, row: DashboardRecord) => "dueAt" in row ? row.dueAt : "createdAt" in row ? row.createdAt || "日期待补" : "created_at" in row ? row.created_at || "日期待补" : "日期待补" }]} /> : <Empty title="当前口径没有匹配记录" description="不是未筛选列表；关闭抽屉即可返回，概览筛选保持不变。" />}</section>)}</div>}</SideSheet>
  </div>;
}
function Panel({ title, note, action, children }: { title: string; note: string; action?: ReactNode; children: ReactNode }) { return <section className="dashboard-panel"><header><div><h2>{title}</h2><p>{note}</p></div>{action}</header>{children}</section>; }
