import { useState } from "react";
import { Button, Input, Modal, Select, Table, TextArea, Toast } from "@douyinfe/semi-ui";
import { IconEdit, IconPlus } from "@douyinfe/semi-icons";
import { PageHeader, StatusTag, TableEntity } from "@/components/CrmUi";
import { useCrm } from "@/stores/crm-store";
import type { CrmTask } from "@/types/crm";
import { dateTime } from "@/utils/format";

const blank = { title: "", relationType: "LEAD" as CrmTask["relationType"], relationId: "", ownerId: "", dueAt: new Date(Date.now() + 86_400_000).toISOString().slice(0, 16), priority: "MEDIUM" as CrmTask["priority"], description: "" };

export function TasksPage() {
  const { state, scoped, currentUser, addTask, updateTask } = useCrm(); const [status, setStatus] = useState("OPEN"); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<CrmTask | null>(null); const [form, setForm] = useState(blank);
  const tasks = scoped(state.tasks).filter((item) => status === "all" || item.status === status); const owners = scoped(state.users.filter((user) => user.role !== "HQ_ADMIN"));
  const relationOptions = form.relationType === "LEAD" ? scoped(state.leads) : form.relationType === "DEAL" ? scoped(state.deals) : form.relationType === "CONTACT" ? scoped(state.contacts) : scoped(state.organizations);
  const start = (task?: CrmTask) => { setEditing(task || null); setForm(task ? { title: task.title, relationType: task.relationType, relationId: task.relationId, ownerId: task.ownerId, dueAt: task.dueAt.slice(0, 16), priority: task.priority, description: task.description } : { ...blank, relationId: scoped(state.leads)[0]?.id || "", ownerId: currentUser.role === "HQ_ADMIN" ? owners[0]?.id || currentUser.id : currentUser.id }); setOpen(true); };
  const save = () => { if (!form.title || !form.relationId || !form.ownerId) { Toast.warning("请完成必填字段"); return; } const owner = state.users.find((user) => user.id === form.ownerId)!; if (editing) updateTask(editing.id, { ...form, dueAt: new Date(form.dueAt).toISOString() }); else addTask({ ...form, distributorId: owner.distributorId, dueAt: new Date(form.dueAt).toISOString(), status: "OPEN" }); setOpen(false); };
  const columns = [{ title: "Task", dataIndex: "title", width: 250, render: (_: unknown, task: CrmTask) => <TableEntity name={task.title} detail={task.description} /> }, { title: "Relation", render: (_: unknown, task: CrmTask) => { const pool = task.relationType === "LEAD" ? state.leads : task.relationType === "DEAL" ? state.deals : task.relationType === "CONTACT" ? state.contacts : state.organizations; return `${task.relationType} · ${pool.find((item) => item.id === task.relationId)?.name || "—"}`; } }, { title: "Owner", dataIndex: "ownerId", render: (value: string, task: CrmTask) => <Select size="small" value={value} onChange={(next) => updateTask(task.id, { ownerId: String(next) })} optionList={owners.map((user) => ({ value: user.id, label: user.name }))} /> }, { title: "Due Date", dataIndex: "dueAt", render: (value: string) => dateTime(value) }, { title: "Priority", dataIndex: "priority" }, { title: "Status", dataIndex: "status", render: (value: CrmTask["status"]) => <StatusTag value={value} label={value} /> }, { title: "Actions", render: (_: unknown, task: CrmTask) => <div className="row-actions"><Button size="small" icon={<IconEdit />} onClick={() => start(task)}>Edit</Button>{task.status === "OPEN" && <><Button size="small" onClick={() => updateTask(task.id, { status: "DONE" })}>Complete</Button><Button size="small" type="tertiary" onClick={() => updateTask(task.id, { status: "CANCELED" })}>Cancel</Button></>}</div> }];
  return <div className="page"><PageHeader title="Tasks" description="跨 Lead、Deal、Contact 与 Organization 的下一步行动。" actions={<Button theme="solid" icon={<IconPlus />} onClick={() => start()}>Create Task</Button>} /><section className="data-surface"><div className="table-toolbar"><Select value={status} onChange={(value) => setStatus(String(value))} optionList={[{ value: "all", label: "All Status" }, { value: "OPEN", label: "Open" }, { value: "DONE", label: "Completed" }, { value: "CANCELED", label: "Canceled" }]} /></div><Table rowKey="id" columns={columns} dataSource={tasks} pagination={{ pageSize: 10 }} scroll={{ x: 1050 }} /></section><Modal visible={open} title={editing ? "Edit Task" : "Create Task"} onCancel={() => setOpen(false)} onOk={save}><div className="form-stack"><label>Title<Input value={form.title} onChange={(value) => setForm((current) => ({ ...current, title: value }))} /></label><label>Relation Type<Select value={form.relationType} onChange={(value) => setForm((current) => ({ ...current, relationType: String(value) as CrmTask["relationType"], relationId: "" }))} optionList={["LEAD", "DEAL", "CONTACT", "ORGANIZATION"].map((value) => ({ value, label: value }))} /></label><label>Relation<Select filter value={form.relationId} onChange={(value) => setForm((current) => ({ ...current, relationId: String(value) }))} optionList={relationOptions.map((item) => ({ value: item.id, label: item.name }))} /></label><label>Owner<Select value={form.ownerId} onChange={(value) => setForm((current) => ({ ...current, ownerId: String(value) }))} optionList={owners.map((user) => ({ value: user.id, label: user.name }))} /></label><label>Due Date<Input type="datetime-local" value={form.dueAt} onChange={(value) => setForm((current) => ({ ...current, dueAt: value }))} /></label><label>Priority<Select value={form.priority} onChange={(value) => setForm((current) => ({ ...current, priority: String(value) as CrmTask["priority"] }))} optionList={["LOW", "MEDIUM", "HIGH"].map((value) => ({ value, label: value }))} /></label><label>Description<TextArea value={form.description} onChange={(value) => setForm((current) => ({ ...current, description: value }))} /></label></div></Modal></div>;
}
