import { useMemo, useState } from "react";
import { Button, Input, Modal, Select, SideSheet, Table, Tag, Toast } from "@douyinfe/semi-ui";
import { IconPlus, IconSearch } from "@douyinfe/semi-icons";
import { DataList, DetailWorkspace, EmptyBlock, LoadingBlock, PageHeader, SideSection, StatusTag, TableEntity } from "@/components/CrmUi";
import { RecordTabs } from "@/features/communication/RecordTabs";
import { dealStageLabels, leadStatusLabels, useCrm } from "@/stores/crm-store";
import type { DealStage, Lead, LeadStatus } from "@/types/crm";
import { date, dateTime, navigate } from "@/utils/format";

const statuses = Object.entries(leadStatusLabels).map(([value, label]) => ({ value, label }));

export function LeadsPage({ id }: { id?: string }) {
  return id ? <LeadDetail id={id} /> : <LeadList />;
}

function LeadList() {
  const { state, currentUser, isHq, scoped, loading, updateLead, addLead } = useCrm();
  const [createOpen, setCreateOpen] = useState(false);
  const [selected, setSelected] = useState<string[]>([]);
  const [filters, setFilters] = useState({ keyword: "", status: "all", ownerId: "all", distributorId: "all", source: "all", product: "all", created: "" });
  const rows = useMemo(() => scoped(state.leads, filters.distributorId).filter((lead) => {
    const organization = state.organizations.find((item) => item.id === lead.organizationId);
    const contact = state.contacts.find((item) => item.id === lead.contactId);
    const haystack = `${lead.name} ${organization?.name} ${contact?.name}`.toLowerCase();
    return (!filters.keyword || haystack.includes(filters.keyword.toLowerCase())) && (filters.status === "all" || lead.status === filters.status) && (filters.ownerId === "all" || lead.ownerId === filters.ownerId) && (filters.source === "all" || lead.source === filters.source) && (filters.product === "all" || lead.productInterest.includes(filters.product)) && (!filters.created || lead.createdAt.slice(0, 10) >= filters.created);
  }), [filters, scoped, state]);
  const owners = scoped(state.users.filter((user) => user.role !== "HQ_ADMIN"));
  const columns = [
    { title: "Lead", dataIndex: "name", width: 260, sorter: (a?: Lead, b?: Lead) => (a?.name || "").localeCompare(b?.name || ""), render: (_: unknown, lead: Lead) => <TableEntity name={lead.name} detail={state.contacts.find((item) => item.id === lead.contactId)?.name} route={`leads/${lead.id}`} /> },
    { title: "Organization", dataIndex: "organizationId", width: 176, render: (value: string) => state.organizations.find((item) => item.id === value)?.name || "—" },
    { title: "Product Interest", dataIndex: "productInterest", width: 220, render: (values: string[]) => <div className="tag-line">{values.map((value) => <Tag size="small" key={value}>{value}</Tag>)}</div> },
    { title: "Status", dataIndex: "status", width: 132, render: (value: LeadStatus, lead: Lead) => <Select size="small" value={value} optionList={statuses} onChange={(next) => updateLead(lead.id, { status: String(next) as LeadStatus })} /> },
    { title: "Owner", dataIndex: "ownerId", width: 142, render: (value: string, lead: Lead) => <Select size="small" value={value} optionList={owners.map((user) => ({ value: user.id, label: user.name }))} onChange={(next) => updateLead(lead.id, { ownerId: String(next) })} /> },
    ...(isHq ? [{ title: "Distributor", dataIndex: "distributorId", width: 156, render: (value: string) => state.distributors.find((item) => item.id === value)?.name }] : []),
    { title: "Last Activity", dataIndex: "lastActivityAt", width: 132, sorter: (a?: Lead, b?: Lead) => (a?.lastActivityAt || "").localeCompare(b?.lastActivityAt || ""), render: (value: string) => dateTime(value) },
    { title: "Created", dataIndex: "createdAt", width: 110, sorter: (a?: Lead, b?: Lead) => (a?.createdAt || "").localeCompare(b?.createdAt || ""), render: (value: string) => date(value) },
  ];
  return <div className="page"><PageHeader title="Leads" description="尚未确认是否构成正式销售机会的潜在线索。" actions={<Button theme="solid" icon={<IconPlus />} onClick={() => setCreateOpen(true)}>Create Lead</Button>} />
    <div className="metric-strip">{([['All Leads', rows.length], ['Qualified', rows.filter((item) => item.status === 'QUALIFIED').length], ['Needs Action', rows.filter((item) => ['NEW', 'CONTACTED'].includes(item.status)).length], ['Converted', rows.filter((item) => item.status === 'CONVERTED').length]] as const).map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
    <section className="data-surface"><div className="table-toolbar"><Input prefix={<IconSearch />} value={filters.keyword} onChange={(value) => setFilters((current) => ({ ...current, keyword: value }))} placeholder="Search Lead, Organization, Contact" showClear />
      <Select value={filters.status} onChange={(value) => setFilters((current) => ({ ...current, status: String(value) }))} optionList={[{ value: "all", label: "All Status" }, ...statuses]} />
      <Select value={filters.ownerId} onChange={(value) => setFilters((current) => ({ ...current, ownerId: String(value) }))} optionList={[{ value: "all", label: "All Owners" }, ...owners.map((user) => ({ value: user.id, label: user.name }))]} />
      {isHq && <Select value={filters.distributorId} onChange={(value) => setFilters((current) => ({ ...current, distributorId: String(value) }))} optionList={[{ value: "all", label: "All Distributors" }, ...state.distributors.map((item) => ({ value: item.id, label: item.name }))]} />}
      <Select value={filters.source} onChange={(value) => setFilters((current) => ({ ...current, source: String(value) }))} optionList={[{ value: "all", label: "All Sources" }, ...Array.from(new Set(state.leads.map((item) => item.source))).map((value) => ({ value, label: value }))]} />
      <Select value={filters.product} onChange={(value) => setFilters((current) => ({ ...current, product: String(value) }))} optionList={[{ value: "all", label: "All Product Interest" }, ...Array.from(new Set(state.leads.flatMap((item) => item.productInterest))).map((value) => ({ value, label: value }))]} />
      <Input type="date" value={filters.created} onChange={(value) => setFilters((current) => ({ ...current, created: value }))} aria-label="Created Date" />
    </div>{selected.length > 0 && <div className="selection-bar"><strong>{selected.length} selected</strong><Button size="small" onClick={() => { selected.forEach((leadId) => updateLead(leadId, { ownerId: currentUser.id })); setSelected([]); }}>Assign to me</Button><Button size="small" onClick={() => { selected.forEach((leadId) => updateLead(leadId, { status: "QUALIFIED" })); setSelected([]); }}>Mark Qualified</Button></div>}
      {loading ? <LoadingBlock /> : rows.length ? <Table columns={columns} dataSource={rows} rowKey="id" pagination={{ pageSize: 10, showSizeChanger: true }} scroll={{ x: 1320 }} rowSelection={{ selectedRowKeys: selected, onChange: (keys?: (string | number)[]) => setSelected((keys || []).map(String)) }} /> : <EmptyBlock title="没有匹配的 Lead" description="调整筛选条件，或创建一条新的 Lead。" action={() => setCreateOpen(true)} />}
    </section><CreateLeadSheet visible={createOpen} onClose={() => setCreateOpen(false)} onCreate={(lead) => { const created = addLead(lead); setCreateOpen(false); navigate(`leads/${created.id}`); }} />
  </div>;
}

function CreateLeadSheet({ visible, onClose, onCreate }: { visible: boolean; onClose: () => void; onCreate: (lead: Omit<Lead, "id" | "createdAt" | "lastActivityAt">) => void }) {
  const { state, currentUser, isHq, scoped } = useCrm();
  const scopedOrganizations = scoped(state.organizations); const scopedContacts = scoped(state.contacts);
  const [form, setForm] = useState({ name: "", organizationId: scopedOrganizations[0]?.id || "", contactId: scopedContacts[0]?.id || "", ownerId: scopedOrganizations[0]?.ownerId || currentUser.id, distributorId: scopedOrganizations[0]?.distributorId || currentUser.distributorId, source: "Website", productInterest: ["Image AR"] as string[] });
  const organization = state.organizations.find((item) => item.id === form.organizationId);
  const submit = () => { if (!form.name || !form.organizationId || !form.contactId) return Toast.warning("请填写 Lead 名称、组织和联系人"); onCreate({ ...form, distributorId: organization?.distributorId || form.distributorId, status: "NEW" }); };
  return <SideSheet visible={visible} width={640} title="Create Lead" onCancel={onClose} footer={<div className="sheet-footer"><Button onClick={onClose}>Cancel</Button><Button theme="solid" onClick={submit}>Create Lead</Button></div>}><div className="form-stack"><label>Lead Name<Input aria-label="Lead Name" value={form.name} onChange={(value) => setForm((current) => ({ ...current, name: value }))} placeholder="e.g. Nike China WebAR Campaign" /></label><label>Organization<Select aria-label="Organization" filter value={form.organizationId} onChange={(value) => { const organizationId = String(value); const linked = state.organizations.find((item) => item.id === organizationId); const contact = state.contacts.find((item) => item.organizationId === organizationId); setForm((current) => ({ ...current, organizationId, contactId: contact?.id || "", distributorId: linked?.distributorId || current.distributorId })); }} optionList={scopedOrganizations.map((item) => ({ value: item.id, label: item.name }))} /></label><label>Primary Contact<Select aria-label="Primary Contact" filter value={form.contactId} onChange={(value) => setForm((current) => ({ ...current, contactId: String(value) }))} optionList={scopedContacts.filter((item) => item.organizationId === form.organizationId).map((item) => ({ value: item.id, label: `${item.name} · ${item.jobTitle}` }))} /></label><label>Product Interest<Select aria-label="Product Interest" multiple value={form.productInterest} onChange={(value) => setForm((current) => ({ ...current, productInterest: value as string[] }))} optionList={state.products.flatMap((product) => product.capabilities.map((item) => ({ value: item.name, label: `${product.name} · ${item.name}` })))} /></label><label>Source<Select aria-label="Source" value={form.source} onChange={(value) => setForm((current) => ({ ...current, source: String(value) }))} optionList={["Website", "Referral", "Exhibition", "LinkedIn", "Partner", "Outbound"].map((value) => ({ value, label: value }))} /></label>{isHq && <p className="form-hint">Distributor scope follows the selected Organization.</p>}</div></SideSheet>;
}

function LeadDetail({ id }: { id: string }) {
  const { state, updateLead } = useCrm(); const lead = state.leads.find((item) => item.id === id); const [convertOpen, setConvertOpen] = useState(false);
  if (!lead) return <div className="page"><EmptyBlock title="Lead 不存在" description="它可能已被重置。" action={() => navigate("leads")} /></div>;
  const organization = state.organizations.find((item) => item.id === lead.organizationId)!; const contact = state.contacts.find((item) => item.id === lead.contactId)!; const owner = state.users.find((item) => item.id === lead.ownerId)!; const distributor = state.distributors.find((item) => item.id === lead.distributorId)!;
  return <><DetailWorkspace eyebrow="Leads / List" title={lead.name} subtitle={`${organization.name} · ${contact.name}`} backRoute="leads" tags={<><StatusTag value={lead.status} label={leadStatusLabels[lead.status]} />{lead.productInterest.map((item) => <Tag size="small" key={item}>{item}</Tag>)}</>} actions={<><Select value={lead.ownerId} onChange={(value) => updateLead(lead.id, { ownerId: String(value) })} optionList={state.users.filter((user) => user.distributorId === lead.distributorId).map((user) => ({ value: user.id, label: user.name }))} /><Select value={lead.status} onChange={(value) => updateLead(lead.id, { status: String(value) as LeadStatus })} optionList={statuses} />{lead.status !== "CONVERTED" && <Button theme="solid" disabled={lead.status !== "QUALIFIED"} onClick={() => setConvertOpen(true)}>Convert to Deal</Button>}</>} tabs={<RecordTabs entityType="LEAD" entityId={lead.id} contactId={lead.contactId} distributorId={lead.distributorId} dataPanel={<section className="data-panel"><PageHeader title="Lead Data" description="来源、产品兴趣与生命周期信息。" /><DataList rows={[["Source", lead.source], ["Status", leadStatusLabels[lead.status]], ["Created", dateTime(lead.createdAt)], ["Last Activity", dateTime(lead.lastActivityAt)], ["Product Interest", lead.productInterest.join(" · ")], ["Converted Deal", lead.convertedDealId ? <a href={`#deals/${lead.convertedDealId}`}>打开 Deal</a> : "—"]]} /></section>} />} sidebar={<><SideSection title="Lead Info"><DataList rows={[["Owner", owner.name], ["Distributor", distributor.name], ["Source", lead.source], ["Created", date(lead.createdAt)]]} /></SideSection><SideSection title="Person"><DataList rows={[["Name", contact.name], ["Job Title", contact.jobTitle], ["Email", contact.email], ["Phone", contact.phone]]} /></SideSection><SideSection title="Organization"><DataList rows={[["Name", <a href={`#organizations/${organization.id}`}>{organization.name}</a>], ["Industry", organization.industry], ["Country", organization.country]]} /></SideSection></>} /><ConvertLeadModal lead={lead} visible={convertOpen} onClose={() => setConvertOpen(false)} /></>;
}

function ConvertLeadModal({ lead, visible, onClose }: { lead: Lead; visible: boolean; onClose: () => void }) {
  const { state, convertLead } = useCrm();
  const [form, setForm] = useState({ name: `${lead.name} Deal`, organizationId: lead.organizationId, primaryContactId: lead.contactId, ownerId: lead.ownerId, productId: state.products[0].id, capabilityIds: [] as string[], expectedClose: new Date(Date.now() + 30 * 86_400_000).toISOString().slice(0, 10), stage: "DISCOVERY" as DealStage });
  const product = state.products.find((item) => item.id === form.productId)!;
  const submit = () => { const deal = convertLead(lead.id, { ...form, expectedClose: new Date(form.expectedClose).toISOString() }); onClose(); navigate(`deals/${deal.id}`); };
  return <Modal visible={visible} title="Convert Lead to Deal" width={680} okText="Convert" cancelText="Cancel" onCancel={onClose} onOk={submit}><div className="form-grid"><label className="wide">Deal Name<Input value={form.name} onChange={(value) => setForm((current) => ({ ...current, name: value }))} /></label><label>Organization<Select value={form.organizationId} onChange={(value) => setForm((current) => ({ ...current, organizationId: String(value) }))} optionList={state.organizations.filter((item) => item.distributorId === lead.distributorId).map((item) => ({ value: item.id, label: item.name }))} /></label><label>Primary Contact<Select value={form.primaryContactId} onChange={(value) => setForm((current) => ({ ...current, primaryContactId: String(value) }))} optionList={state.contacts.filter((item) => item.organizationId === form.organizationId).map((item) => ({ value: item.id, label: item.name }))} /></label><label>Owner<Select value={form.ownerId} onChange={(value) => setForm((current) => ({ ...current, ownerId: String(value) }))} optionList={state.users.filter((item) => item.distributorId === lead.distributorId).map((item) => ({ value: item.id, label: item.name }))} /></label><label>Product<Select value={form.productId} onChange={(value) => setForm((current) => ({ ...current, productId: String(value), capabilityIds: [] }))} optionList={state.products.filter((item) => item.status === "ACTIVE").map((item) => ({ value: item.id, label: item.name }))} /></label><label>Expected Close Date<Input type="date" value={form.expectedClose} onChange={(value) => setForm((current) => ({ ...current, expectedClose: value }))} /></label><label>Initial Stage<Select value={form.stage} onChange={(value) => setForm((current) => ({ ...current, stage: String(value) as DealStage }))} optionList={(["DISCOVERY", "SOLUTION"] as DealStage[]).map((value) => ({ value, label: dealStageLabels[value] }))} /></label><label className="wide">Add-ons<Select multiple value={form.capabilityIds} onChange={(value) => setForm((current) => ({ ...current, capabilityIds: value as string[] }))} optionList={product.capabilities.map((item) => ({ value: item.id, label: item.name }))} /></label></div></Modal>;
}
