import { useMemo, useState } from "react";
import { Button, Input, Select, SideSheet, TabPane, Table, Tabs, Tag, Toast } from "@douyinfe/semi-ui";
import { IconPlus, IconSearch } from "@douyinfe/semi-icons";
import { ActivityTimeline } from "@/components/ActivityTimeline";
import { DataList, DetailWorkspace, EmptyBlock, PageHeader, SideSection, TableEntity } from "@/components/CrmUi";
import { EntityAttachments, EntityNotes } from "@/features/communication/RecordTabs";
import { useCrm } from "@/stores/crm-store";
import type { Contact, Organization } from "@/types/crm";
import { dateTime, navigate } from "@/utils/format";

export function OrganizationsPage({ id }: { id?: string }) { return id ? <OrganizationDetail id={id} /> : <OrganizationList />; }
export function ContactsPage({ id }: { id?: string }) { return id ? <ContactDetail id={id} /> : <ContactList />; }

function OrganizationList() {
  const { state, scoped, isHq, addOrganization } = useCrm(); const [keyword, setKeyword] = useState(""); const [open, setOpen] = useState(false);
  const rows = useMemo(() => scoped(state.organizations).filter((item) => item.name.toLowerCase().includes(keyword.toLowerCase()) || item.industry.toLowerCase().includes(keyword.toLowerCase())), [keyword, scoped, state.organizations]);
  const columns = [
    { title: "Organization", dataIndex: "name", width: 230, render: (_: unknown, item: Organization) => <TableEntity name={item.name} detail={item.industry} route={`organizations/${item.id}`} /> },
    { title: "Industry", dataIndex: "industry", width: 150 }, { title: "Country", dataIndex: "country", width: 120 },
    { title: "Contacts", width: 88, render: (_: unknown, item: Organization) => state.contacts.filter((contact) => contact.organizationId === item.id).length },
    { title: "Open Leads", width: 90, render: (_: unknown, item: Organization) => state.leads.filter((lead) => lead.organizationId === item.id && !["CONVERTED", "UNQUALIFIED"].includes(lead.status)).length },
    { title: "Open Deals", width: 90, render: (_: unknown, item: Organization) => state.deals.filter((deal) => deal.organizationId === item.id && !["WON", "LOST"].includes(deal.stage)).length },
    { title: "Owner", dataIndex: "ownerId", width: 120, render: (value: string) => state.users.find((user) => user.id === value)?.name },
    ...(isHq ? [{ title: "Distributor", dataIndex: "distributorId", width: 150, render: (value: string) => state.distributors.find((item) => item.id === value)?.name }] : []),
    { title: "Last Activity", dataIndex: "lastActivityAt", width: 130, render: (value: string) => dateTime(value) },
  ];
  return <div className="page"><PageHeader title="Organizations" description="客户公司与机构的 Customer 360 主档。" actions={<Button theme="solid" icon={<IconPlus />} onClick={() => setOpen(true)}>Create Organization</Button>} /><section className="data-surface"><div className="table-toolbar"><Input prefix={<IconSearch />} value={keyword} onChange={setKeyword} showClear placeholder="Search Organization or Industry" /></div>{rows.length ? <Table rowKey="id" columns={columns} dataSource={rows} pagination={{ pageSize: 10 }} scroll={{ x: 1100 }} /> : <EmptyBlock title="没有匹配的组织" action={() => setOpen(true)} />}</section><OrganizationSheet visible={open} onClose={() => setOpen(false)} onSave={(input) => { const created = addOrganization(input); setOpen(false); navigate(`organizations/${created.id}`); }} /></div>;
}

function OrganizationSheet({ visible, onClose, onSave }: { visible: boolean; onClose: () => void; onSave: (value: Omit<Organization, "id" | "lastActivityAt">) => void }) {
  const { state, currentUser, isHq } = useCrm(); const [form, setForm] = useState({ name: "", industry: "", country: "", ownerId: currentUser.id, distributorId: currentUser.distributorId });
  return <SideSheet visible={visible} title="Create Organization" width={560} onCancel={onClose} footer={<div className="sheet-footer"><Button onClick={onClose}>Cancel</Button><Button theme="solid" onClick={() => form.name && form.industry ? onSave(form) : Toast.warning("请填写名称与行业")}>Create</Button></div>}><div className="form-stack"><label>Name<Input value={form.name} onChange={(value) => setForm((current) => ({ ...current, name: value }))} /></label><label>Industry<Input value={form.industry} onChange={(value) => setForm((current) => ({ ...current, industry: value }))} /></label><label>Country<Input value={form.country} onChange={(value) => setForm((current) => ({ ...current, country: value }))} /></label>{isHq && <label>Distributor<Select value={form.distributorId} onChange={(value) => { const distributorId = String(value); const owner = state.users.find((user) => user.distributorId === distributorId); setForm((current) => ({ ...current, distributorId, ownerId: owner?.id || current.ownerId })); }} optionList={state.distributors.filter((item) => item.id !== "dist-hq").map((item) => ({ value: item.id, label: item.name }))} /></label>}<label>Owner<Select value={form.ownerId} onChange={(value) => setForm((current) => ({ ...current, ownerId: String(value) }))} optionList={state.users.filter((user) => user.distributorId === form.distributorId).map((item) => ({ value: item.id, label: item.name }))} /></label></div></SideSheet>;
}

function OrganizationDetail({ id }: { id: string }) {
  const { state } = useCrm(); const item = state.organizations.find((organization) => organization.id === id); if (!item) return <div className="page"><EmptyBlock title="组织不存在" action={() => navigate("organizations")} /></div>;
  const contacts = state.contacts.filter((contact) => contact.organizationId === id); const leads = state.leads.filter((lead) => lead.organizationId === id); const deals = state.deals.filter((deal) => deal.organizationId === id); const owner = state.users.find((user) => user.id === item.ownerId); const distributor = state.distributors.find((current) => current.id === item.distributorId);
  const related = (rows: Array<{ id: string; name: string }>, route: string) => <div className="related-list">{rows.map((row) => <a key={row.id} href={`#${route}/${row.id}`}>{row.name}</a>)}</div>;
  return <DetailWorkspace eyebrow="Organizations / Customer 360" title={item.name} subtitle={`${item.industry} · ${item.country}`} backRoute="organizations" tags={<Tag color="green">Active Customer</Tag>} tabs={<Tabs className="record-tabs"><TabPane tab="Overview" itemKey="overview"><section className="data-panel"><PageHeader title="Customer 360" description="组织关系、联系人与销售进展的统一视图。" /><div className="metric-strip"><div><span>Contacts</span><strong>{contacts.length}</strong></div><div><span>Open Leads</span><strong>{leads.filter((lead) => !["CONVERTED", "UNQUALIFIED"].includes(lead.status)).length}</strong></div><div><span>Open Deals</span><strong>{deals.filter((deal) => !["WON", "LOST"].includes(deal.stage)).length}</strong></div><div><span>Won Deals</span><strong>{deals.filter((deal) => deal.stage === "WON").length}</strong></div></div></section></TabPane><TabPane tab="Contacts" itemKey="contacts">{related(contacts, "contacts")}</TabPane><TabPane tab="Leads" itemKey="leads">{related(leads, "leads")}</TabPane><TabPane tab="Deals" itemKey="deals">{related(deals, "deals")}</TabPane><TabPane tab="Activity" itemKey="activity"><ActivityTimeline entityType="ORGANIZATION" entityId={id} /></TabPane><TabPane tab="Attachments" itemKey="attachments"><EntityAttachments entityType="ORGANIZATION" entityId={id} /></TabPane></Tabs>} sidebar={<><SideSection title="Organization"><DataList rows={[["Industry", item.industry], ["Country", item.country], ["Owner", owner?.name], ["Distributor", distributor?.name], ["Last Activity", dateTime(item.lastActivityAt)]]} /></SideSection><SideSection title="Key Contacts">{related(contacts.slice(0, 5), "contacts")}</SideSection></>} />;
}

function ContactList() {
  const { state, scoped, isHq, addContact } = useCrm(); const [keyword, setKeyword] = useState(""); const [open, setOpen] = useState(false);
  const rows = scoped(state.contacts).filter((item) => `${item.name} ${item.email}`.toLowerCase().includes(keyword.toLowerCase()));
  const columns = [{ title: "Contact", dataIndex: "name", width: 220, render: (_: unknown, item: Contact) => <TableEntity name={item.name} detail={item.jobTitle} route={`contacts/${item.id}`} /> }, { title: "Organization", dataIndex: "organizationId", width: 180, render: (value: string) => state.organizations.find((item) => item.id === value)?.name }, { title: "Email", dataIndex: "email", width: 220 }, { title: "Phone", dataIndex: "phone", width: 160 }, { title: "Country", dataIndex: "country", width: 110 }, { title: "Owner", dataIndex: "ownerId", width: 120, render: (value: string) => state.users.find((item) => item.id === value)?.name }, ...(isHq ? [{ title: "Distributor", dataIndex: "distributorId", width: 150, render: (value: string) => state.distributors.find((item) => item.id === value)?.name }] : []), { title: "Last Activity", dataIndex: "lastActivityAt", width: 130, render: (value: string) => dateTime(value) }];
  return <div className="page"><PageHeader title="Contacts" description="具体联系人、组织关系与跨销售周期互动。" actions={<Button theme="solid" icon={<IconPlus />} onClick={() => setOpen(true)}>Create Contact</Button>} /><section className="data-surface"><div className="table-toolbar"><Input prefix={<IconSearch />} value={keyword} onChange={setKeyword} showClear placeholder="Search Contact or Email" /></div><Table rowKey="id" columns={columns} dataSource={rows} pagination={{ pageSize: 10 }} scroll={{ x: 1100 }} /></section><ContactSheet visible={open} onClose={() => setOpen(false)} onSave={(input) => { const created = addContact(input); setOpen(false); navigate(`contacts/${created.id}`); }} /></div>;
}

function ContactSheet({ visible, onClose, onSave }: { visible: boolean; onClose: () => void; onSave: (value: Omit<Contact, "id" | "lastActivityAt">) => void }) {
  const { state, currentUser, scoped } = useCrm(); const organizations = scoped(state.organizations); const [form, setForm] = useState({ name: "", organizationId: organizations[0]?.id || "", jobTitle: "", email: "", phone: "", linkedin: "", whatsapp: "", wechat: "", country: "", ownerId: currentUser.id, distributorId: currentUser.distributorId });
  return <SideSheet visible={visible} title="Create Contact" width={620} onCancel={onClose} footer={<div className="sheet-footer"><Button onClick={onClose}>Cancel</Button><Button theme="solid" onClick={() => form.name && form.email ? onSave(form) : Toast.warning("请填写姓名和 Email")}>Create</Button></div>}><div className="form-grid"><label>Name<Input value={form.name} onChange={(value) => setForm((current) => ({ ...current, name: value }))} /></label><label>Organization<Select filter value={form.organizationId} onChange={(value) => { const organizationId = String(value); const organization = state.organizations.find((item) => item.id === organizationId); setForm((current) => ({ ...current, organizationId, ownerId: organization?.ownerId || current.ownerId, distributorId: organization?.distributorId || current.distributorId, country: organization?.country || current.country })); }} optionList={organizations.map((item) => ({ value: item.id, label: item.name }))} /></label><label>Job Title<Input value={form.jobTitle} onChange={(value) => setForm((current) => ({ ...current, jobTitle: value }))} /></label><label>Email<Input value={form.email} onChange={(value) => setForm((current) => ({ ...current, email: value }))} /></label><label>Phone<Input value={form.phone} onChange={(value) => setForm((current) => ({ ...current, phone: value }))} /></label><label>LinkedIn<Input value={form.linkedin} onChange={(value) => setForm((current) => ({ ...current, linkedin: value }))} /></label><label>WhatsApp<Input value={form.whatsapp} onChange={(value) => setForm((current) => ({ ...current, whatsapp: value }))} /></label><label>WeChat<Input value={form.wechat} onChange={(value) => setForm((current) => ({ ...current, wechat: value }))} /></label></div></SideSheet>;
}

function ContactDetail({ id }: { id: string }) {
  const { state } = useCrm(); const item = state.contacts.find((contact) => contact.id === id); if (!item) return <div className="page"><EmptyBlock title="联系人不存在" action={() => navigate("contacts")} /></div>;
  const organization = state.organizations.find((current) => current.id === item.organizationId)!; const leads = state.leads.filter((lead) => lead.contactId === id); const deals = state.deals.filter((deal) => deal.primaryContactId === id); const tasks = state.tasks.filter((task) => task.relationType === "CONTACT" && task.relationId === id);
  const related = (rows: Array<{ id: string; name: string }>, route: string) => <div className="related-list">{rows.map((row) => <a key={row.id} href={`#${route}/${row.id}`}>{row.name}</a>)}</div>;
  return <DetailWorkspace eyebrow="Contacts / Profile" title={item.name} subtitle={`${item.jobTitle} · ${organization.name}`} backRoute="contacts" tabs={<Tabs className="record-tabs"><TabPane tab="Profile" itemKey="profile"><section className="data-panel"><PageHeader title="Contact Profile" description="统一的 Person 视图。" /><DataList rows={[["Organization", organization.name], ["Job Title", item.jobTitle], ["Email", item.email], ["Phone", item.phone], ["LinkedIn", item.linkedin], ["WhatsApp", item.whatsapp], ["WeChat", item.wechat], ["Country", item.country]]} /></section></TabPane><TabPane tab="Activity" itemKey="activity"><ActivityTimeline entityType="CONTACT" entityId={id} /></TabPane><TabPane tab="Leads" itemKey="leads">{related(leads, "leads")}</TabPane><TabPane tab="Deals" itemKey="deals">{related(deals, "deals")}</TabPane><TabPane tab="Tasks" itemKey="tasks"><div className="related-list">{tasks.map((task) => <span key={task.id}>{task.title}</span>)}</div></TabPane><TabPane tab="Notes" itemKey="notes"><EntityNotes entityType="CONTACT" entityId={id} /></TabPane><TabPane tab="Attachments" itemKey="attachments"><EntityAttachments entityType="CONTACT" entityId={id} /></TabPane></Tabs>} sidebar={<><SideSection title="Organization"><DataList rows={[["Name", <a href={`#organizations/${organization.id}`}>{organization.name}</a>], ["Industry", organization.industry], ["Country", organization.country]]} /></SideSection><SideSection title="Owner"><DataList rows={[["Name", state.users.find((user) => user.id === item.ownerId)?.name], ["Distributor", state.distributors.find((current) => current.id === item.distributorId)?.name]]} /></SideSection></>} />;
}
