import { useMemo, useState } from "react";
import { Button, Input, RadioGroup, Radio, Select, Table, Tag } from "@douyinfe/semi-ui";
import { IconGridView, IconListView, IconSearch } from "@douyinfe/semi-icons";
import { DataList, DetailWorkspace, EmptyBlock, LoadingBlock, PageHeader, SideSection, StatusTag, TableEntity } from "@/components/CrmUi";
import { RecordTabs } from "@/features/communication/RecordTabs";
import { dealStageLabels, useCrm } from "@/stores/crm-store";
import { getAssignableOwnersForDistributor, isTerminalDeal } from "@/stores/crm-model";
import type { Deal, DealStage } from "@/types/crm";
import { date, dateTime, navigate } from "@/utils/format";

const stages = Object.entries(dealStageLabels).map(([value, label]) => ({ value, label }));

export function DealsPage({ id }: { id?: string }) { return id ? <DealDetail id={id} /> : <DealList />; }

function DealList() {
  const { state, isHq, canWrite, scoped, loading, updateDeal } = useCrm(); const [view, setView] = useState<"list" | "kanban">("list");
  const [filters, setFilters] = useState({ keyword: "", stage: "all", distributorId: "all", productId: "all" });
  const rows = useMemo(() => scoped(state.deals, filters.distributorId).filter((deal) => (!filters.keyword || deal.name.toLowerCase().includes(filters.keyword.toLowerCase())) && (filters.stage === "all" || deal.stage === filters.stage) && (filters.productId === "all" || deal.productId === filters.productId)), [filters, scoped, state.deals]);
  const columns = [
    { title: "Deal", dataIndex: "name", width: 270, sorter: (a?: Deal, b?: Deal) => (a?.name || "").localeCompare(b?.name || ""), render: (_: unknown, deal: Deal) => <TableEntity name={deal.name} detail={state.organizations.find((item) => item.id === deal.organizationId)?.name} route={`deals/${deal.id}`} /> },
    { title: "Product", dataIndex: "productId", width: 132, render: (value: string) => state.products.find((item) => item.id === value)?.name },
    { title: "Add-ons", dataIndex: "capabilityIds", width: 240, render: (ids: string[], deal: Deal) => <div className="tag-line">{ids.map((id) => state.products.find((item) => item.id === deal.productId)?.capabilities.find((item) => item.id === id)?.name).filter(Boolean).map((name) => <Tag size="small" key={name}>{name}</Tag>)}</div> },
    { title: "Stage", dataIndex: "stage", width: 132, render: (value: DealStage, deal: Deal) => <Select disabled={!canWrite || isTerminalDeal(deal)} size="small" value={value} onChange={(next) => updateDeal(deal.id, { stage: String(next) as DealStage })} optionList={stages} /> },
    { title: "Owner", dataIndex: "ownerId", width: 120, render: (value: string) => state.users.find((item) => item.id === value)?.name },
    ...(isHq ? [{ title: "Distributor", dataIndex: "distributorId", width: 150, render: (value: string) => state.distributors.find((item) => item.id === value)?.name }] : []),
    { title: "Expected Close", dataIndex: "expectedClose", width: 130, sorter: (a?: Deal, b?: Deal) => (a?.expectedClose || "").localeCompare(b?.expectedClose || ""), render: (value: string) => date(value) },
    { title: "Last Activity", dataIndex: "lastActivityAt", width: 126, render: (value: string) => dateTime(value) },
  ];
  return <div className="page"><PageHeader title="Deals" description="已经确认存在、正在积极推进的正式销售机会。" actions={<RadioGroup type="button" value={view} onChange={(event) => setView(event.target.value)}><Radio value="list"><IconListView /> List</Radio><Radio value="kanban"><IconGridView /> Kanban</Radio></RadioGroup>} />
    <div className="metric-strip">{([['Open Deals', rows.filter((item) => !['WON','LOST'].includes(item.stage)).length], ['Discovery', rows.filter((item) => item.stage === 'DISCOVERY').length], ['Won', rows.filter((item) => item.stage === 'WON').length], ['Lost', rows.filter((item) => item.stage === 'LOST').length]] as const).map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
    <section className="data-surface"><div className="table-toolbar"><Input prefix={<IconSearch />} value={filters.keyword} onChange={(value) => setFilters((current) => ({ ...current, keyword: value }))} placeholder="Search Deal" showClear /><Select filter value={filters.stage} onChange={(value) => setFilters((current) => ({ ...current, stage: String(value) }))} optionList={[{ value: "all", label: "All Stages" }, ...stages]} /><Select value={filters.productId} onChange={(value) => setFilters((current) => ({ ...current, productId: String(value) }))} optionList={[{ value: "all", label: "All Products" }, ...state.products.map((item) => ({ value: item.id, label: item.name }))]} />{isHq && <Select value={filters.distributorId} onChange={(value) => setFilters((current) => ({ ...current, distributorId: String(value) }))} optionList={[{ value: "all", label: "All Distributors" }, ...state.distributors.map((item) => ({ value: item.id, label: item.name }))]} />}</div>{loading ? <LoadingBlock /> : !rows.length ? <EmptyBlock title="没有匹配的 Deal" description="调整筛选条件，或从 Qualified Lead 转换。" /> : view === "list" ? <Table columns={columns} dataSource={rows} rowKey="id" pagination={{ pageSize: 10 }} scroll={{ x: 1280 }} /> : <DealKanban deals={rows} />}</section>
  </div>;
}

function DealKanban({ deals }: { deals: Deal[] }) {
  const { state, updateDeal, canWrite } = useCrm(); const [dragging, setDragging] = useState("");
  return <div className="kanban" aria-label="Deal Pipeline">{(Object.keys(dealStageLabels) as DealStage[]).map((stage) => <section key={stage} className="kanban-column" onDragOver={(event) => event.preventDefault()} onDrop={() => { const deal = deals.find((item) => item.id === dragging); if (canWrite && deal && !isTerminalDeal(deal) && deal.stage !== stage) updateDeal(deal.id, { stage }, `${dealStageLabels[deal.stage]} → ${dealStageLabels[stage]}`); setDragging(""); }}><header><strong>{dealStageLabels[stage]}</strong><span>{deals.filter((item) => item.stage === stage).length}</span></header><div>{deals.filter((item) => item.stage === stage).map((deal) => { const organization = state.organizations.find((item) => item.id === deal.organizationId); const product = state.products.find((item) => item.id === deal.productId); return <article draggable={canWrite && !isTerminalDeal(deal)} key={deal.id} className={`deal-card ${dragging === deal.id ? "is-dragging" : ""}`} onDragStart={() => setDragging(deal.id)} onDragEnd={() => setDragging("")}><a href={`#deals/${deal.id}`}>{deal.name}</a><p>{organization?.name}</p><div className="deal-card-tags"><Tag size="small">{product?.name}</Tag>{deal.capabilityIds.slice(0, 2).map((id) => <Tag size="small" key={id}>{product?.capabilities.find((item) => item.id === id)?.name}</Tag>)}</div><footer><span>{state.users.find((item) => item.id === deal.ownerId)?.name}</span><time>{date(deal.expectedClose)}</time></footer></article>; })}</div></section>)}</div>;
}

function DealDetail({ id }: { id: string }) {
  const { state, updateDeal, canWrite } = useCrm(); const deal = state.deals.find((item) => item.id === id);
  if (!deal) return <div className="page"><EmptyBlock title="Deal 不存在" action={() => navigate("deals")} /></div>;
  const organization = state.organizations.find((item) => item.id === deal.organizationId)!; const contact = state.contacts.find((item) => item.id === deal.primaryContactId)!; const owner = state.users.find((item) => item.id === deal.ownerId)!; const distributor = state.distributors.find((item) => item.id === deal.distributorId)!; const product = state.products.find((item) => item.id === deal.productId)!;
  if (!organization || !contact || !owner || !distributor || !product) return <div className="page"><EmptyBlock title="Deal 关联资料缺失，待核验" description="原始记录已保留；缺失的组织、联系人、负责人、分销商或产品不会自动补建。" action={() => navigate("deals")} /></div>;
  const capabilityNames = deal.capabilityIds.map((id) => product.capabilities.find((item) => item.id === id)?.name).filter(Boolean);
  return <DetailWorkspace eyebrow="Deals / Pipeline" title={deal.name} subtitle={`${organization.name} · ${product.name}`} backRoute="deals" tags={<><StatusTag value={deal.stage} label={dealStageLabels[deal.stage]} />{capabilityNames.map((item) => <Tag size="small" key={item}>{item}</Tag>)}</>} actions={<><Select disabled={!canWrite} aria-label="Deal Owner" value={deal.ownerId} onChange={(value) => updateDeal(deal.id, { ownerId: String(value) })} optionList={getAssignableOwnersForDistributor(state.users, deal.distributorId).map((user) => ({ value: user.id, label: user.name }))} /><Select disabled={!canWrite || isTerminalDeal(deal)} aria-label="Deal Stage" value={deal.stage} onChange={(value) => updateDeal(deal.id, { stage: String(value) as DealStage })} optionList={stages} /><Button disabled={!canWrite || isTerminalDeal(deal)} type="tertiary" onClick={() => updateDeal(deal.id, { stage: "LOST" })}>Mark Lost</Button><Button disabled={!canWrite || isTerminalDeal(deal)} theme="solid" onClick={() => updateDeal(deal.id, { stage: "WON" })}>Mark Won</Button></>} tabs={<RecordTabs entityType="DEAL" entityId={deal.id} contactId={deal.primaryContactId} distributorId={deal.distributorId} dataPanel={<section className="data-panel"><PageHeader title="Deal Data" description="Deal 推进、产品与来源信息。" /><DataList rows={[["Stage", dealStageLabels[deal.stage]], ["Expected Close", date(deal.expectedClose)], ["Probability", `${deal.probability}%`], ["Product", product.name], ["Add-ons", capabilityNames.join(" · ")], ["Source Lead", deal.sourceLeadId ? <a href={`#leads/${deal.sourceLeadId}`}>打开 Source Lead</a> : "—"]]} /></section>} />} sidebar={<><SideSection title="Deal Details"><DataList rows={[["Organization", organization.name], ["Distributor", distributor.name], ["Owner", owner.name], ["Stage", dealStageLabels[deal.stage]], ["Expected Close", date(deal.expectedClose)], ["Probability", `${deal.probability}%`]]} /></SideSection><SideSection title="Product"><label className="side-field">Product<Select disabled={!canWrite} aria-label="Deal Product" value={deal.productId} onChange={(value) => updateDeal(deal.id, { productId: String(value), capabilityIds: [] })} optionList={state.products.filter((item) => item.status === "ACTIVE").map((item) => ({ value: item.id, label: item.name }))} /></label><label className="side-field">Add-ons<Select disabled={!canWrite} aria-label="Deal Add-ons" multiple value={deal.capabilityIds} onChange={(value) => updateDeal(deal.id, { capabilityIds: value as string[] })} optionList={product.capabilities.filter((item) => item.enabled).map((item) => ({ value: item.id, label: item.name }))} /></label></SideSection><SideSection title="Primary Contact"><DataList rows={[["Name", contact.name], ["Job Title", contact.jobTitle], ["Email", contact.email], ["Phone", contact.phone]]} /></SideSection></>} />;
}
